# 
# Hinemos (http://www.hinemos.info/)
#    common configurations for build
# 
# Copyright (c) 2023 NTT DATA INTELLILINK Corporation. All rights reserved.
# 

# --- hinemos ---
version=7.2.0
version.short=720
version.major=7.2
version.major.short=72
version.tool=7.2.a
version.tool.short=72a
version.excel=7.2.a
version.unix.package=7.2.x_20260422
required.version=7.2.0
ha.version.tool=@HA_VERSION_TOOL@

copyright.year=2026

platform.notify.schemarevision=4
cloud.clouduser.schemarevision=3

manifest.hinemos.version=7.0.4/7.1.2/7.2.0
manifest.ha.hinemos.version=7.0/7.1/7.2
manifest.ha.option.version=7.0.e/7.1.c/7.2.a

manifest.xcloud.option.version=7.0.e/7.1.c/7.2.a

manager.product.code=fc020e33-50b7-409a-8fe7-d2b07e83f933
manager.upgrade.code=60c93e63-c1a0-4bc5-9b5f-ba30b1271115
client.web.product.code=cb9a21d3-c45c-4aa4-8b3c-5b0f578c09fa
client.web.upgrade.code=620c0f85-ed09-46f2-8954-62df80ebfd9a
agent.product.code=686136b5-6727-4c31-9ae9-512e0582f186
xcloud.aws.manager.product.code=a0a8f6e0-5621-47f5-80dd-44929e8ca006
xcloud.aws.manager.upgrade.code=9d8ace7f-7a3b-46fe-a09d-0e613c5b763b
xcloud.aws.client.product.code=a652e792-fc68-4f5d-be22-456bd48ec082
xcloud.aws.client.upgrade.code=873de47c-34ea-4656-bf4c-f7ef5355d057
xcloud.azure.manager.product.code=43b5fe1a-6f1b-4d23-a7c9-0996ce1e4d40
xcloud.azure.manager.upgrade.code=8605c1c9-e517-4412-9614-b0d4c6b094c8
xcloud.azure.client.product.code=94d08a5a-7493-45bd-9223-d3390673f8b6
xcloud.azure.client.upgrade.code=2288d6de-4a83-44e3-9f17-a168a820c7f8
xcloud.hyperv.manager.product.code=4e287c18-e7c2-404b-90c5-e6079b577a85
xcloud.hyperv.manager.upgrade.code=27a3d218-49c5-4534-95de-b6bc333a13dd
xcloud.hyperv.client.product.code=9e679c6e-b089-4ec5-875e-2a81c18219c9
xcloud.hyperv.client.upgrade.code=33ff2df6-834e-4e70-95a4-7f89d8c68ee5
xcloud.vmware.manager.product.code=667855ff-27e6-48b1-9b24-3d5175cef1a5
xcloud.vmware.manager.upgrade.code=1c5325ce-8213-4e1f-a158-589d73297750
xcloud.vmware.client.product.code=fdcda2a6-8ec3-4b73-b00a-7e1ce65b9ff8
xcloud.vmware.client.upgrade.code=c865505b-8fb2-4ba1-879f-7a0ba2f0b89f
xcloud.oci.manager.product.code=6bee1dea-acda-4c7a-b081-0fc5e63601b4
xcloud.oci.manager.upgrade.code=1b35ba76-4939-46eb-94fa-f9de2c130546
xcloud.oci.client.product.code=edd82c42-09c8-43a0-81f3-65460615ee35
xcloud.oci.client.upgrade.code=e50f35af-f3cd-4779-aa17-47f3e2a4ec94
xcloud.gcp.manager.product.code=7240819f-8601-4be1-b2ee-d08eee45f7e9
xcloud.gcp.manager.upgrade.code=fc887398-3580-4aa7-9376-e8306f4fe4f1
xcloud.gcp.client.product.code=01b4f727-9511-4dd8-a114-8be37f06d748
xcloud.gcp.client.upgrade.code=f1e050d9-0eeb-4889-88dd-1852fa957686
xcloud.kvm.manager.product.code=DO NOT USE IT
xcloud.kvm.manager.upgrade.code=DO NOT USE IT
xcloud.kvm.client.product.code=DO NOT USE IT
xcloud.kvm.client.upgrade.code=DO NOT USE IT
ha.product.code=e2aef6da-b150-4756-b093-14c643d120d4
ha.upgrade.code=557f8fae-6dc0-4b87-9fe8-a9ddf01172a1

doc.commandline.ja.name=ja_CommandLine_7.2_rev1
doc.commandline.en.name=en_CommandLine_7.2_rev1
doc.commandline.ja.package.name=ja_CommandLine_7.2_doc_20260422.zip
doc.commandline.en.package.name=en_CommandLine_7.2_doc_20260422.zip
doc.commandline.importexporttool.ja.package.name=ja_CommandLine_ImportExport_7.2_rev1
doc.commandline.importexporttool.en.package.name=en_CommandLine_ImportExport_7.2_rev1

doc.restapi.ja.name=ja_RestAPI_7.2_rev1
doc.restapi.en.name=en_RestAPI_7.2_rev1
