language: java
#jdk:
#  # - openjdk7 # Execution failed for task ':manager:compileJava'. Could not target platform: 'Java SE 8' using tool chain: 'JDK 7 (1.7)'.
#  - openjdk8

# Deal with multi-projects repo
matrix:
  include:
  - name: "Build common"
    jdk:
      - openjdk7
      - openjdk8
    env: SUB_PROJECT=common
  - name: "Build manager"
    jdk: openjdk8
    env: SUB_PROJECT=manager
  - name: "Build agent"
    jdk: openjdk8
    env: SUB_PROJECT=agent
script: gradle :$SUB_PROJECT:build
