language: java
jdk:
  # - openjdk7 # Execution failed for task ':manager:compileJava'. Could not target platform: 'Java SE 8' using tool chain: 'JDK 7 (1.7)'.
  - openjdk8

before_install:
  - chmod +x gradlew
  # OR git update-index --chmod=+x gradlew

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

# Deal with multi-projects repo
matrix:
  include:
  - name: "Build common"
    env: SUB_PROJECT=common
  - name: "Build manager"
    env: SUB_PROJECT=manager
  - name: "Build agent"
    env: SUB_PROJECT=agent

script:
  - gradlew :$SUB_PROJECT:build
  - gradlew :$SUB_PROJECT:jacocoTestReport
after_script:
  - cd $SUB_PROJECT/src/main/java/
  - ../../../../cc-test-reporter format-coverage ../../../build/reports/jacoco/test/jacocoTestReport.xml -t jacoco
  - ../../../../cc-test-reporter after-build -t jacoco --exit-code $TRAVIS_TEST_RESULT
  - cd ../../../../
