language: java
jdk:
  - openjdk7
  - openjdk8

# Deal with multi-projects repo
matrix:
  include:
  - name: "Build common"
    jdk:
      - openjdk7
      - openjdk8
    env: SUB_PROJECT=common
    script: gradle :$SUB_PROJECT:build
