/*
 * Copyright (c) 2018 NTT DATA INTELLILINK Corporation. All rights reserved.
 *
 * Hinemos (http://www.hinemos.info/)
 *
 * See the LICENSE file for licensing information.
 */

package com.clustercontrol.commons.util;

import com.clustercontrol.accesscontrol.bean.UserIdConstant;
import com.clustercontrol.bean.SnmpVersionConstant;
import com.clustercontrol.commons.bean.HinemosPropertyBean;
import com.clustercontrol.infra.bean.InfraNodeInputConstant;
import com.clustercontrol.jobmanagement.factory.CreateHulftJob;
import com.clustercontrol.maintenance.HinemosPropertyTypeConstant;
import com.clustercontrol.maintenance.model.HinemosPropertyInfo;
import com.clustercontrol.maintenance.session.HinemosPropertyControllerBean;
import com.clustercontrol.ping.bean.PingRunCountConstant;
import com.clustercontrol.ping.bean.PingRunIntervalConstant;
import com.clustercontrol.plugin.impl.AsyncWorkerPlugin;
import com.clustercontrol.repository.session.RepositoryControllerBean;
import com.clustercontrol.systemlog.bean.SyslogMessage;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.TimeZone;

/**
 * HinemosPropertyのデフォルト値を格納するクラス<BR>
 *
 * @version 6.1.0
 * @since 6.1.0
 */
public enum HinemosPropertyCommon implements HinemosPropertyAbstract {

	agent_connection_dnsname(HinemosPropertyBean.string("")),
	agent_connection_ipaddres(HinemosPropertyBean.string("")),
	collect_graph_timeout_reporting(HinemosPropertyBean.numeric(50000L)),
	collect_graph_timeout(HinemosPropertyBean.numeric(50000L)),
	collect_logcount_thread_pool_size(HinemosPropertyBean.numeric(1L)),
	collect_logcount_timeout(HinemosPropertyBean.numeric(15000L)),
	common_agent_discovery_pingport(HinemosPropertyBean.numeric(24005L)),
	common_db_connectionpool_stats_threshold(HinemosPropertyBean.numeric(12L)),
	common_invalid_char_replace(HinemosPropertyBean.bool(false)),
	common_invalid_char_replace_to(HinemosPropertyBean.string("?")),
	common_scheduler_startup_delay(HinemosPropertyBean.numeric(60L)),
	common_time_offset(HinemosPropertyBean.numeric(0L)),
	common_timezone(HinemosPropertyBean.numeric( Long.valueOf(TimeZone.getDefault().getRawOffset()))),
	hinemos_selfcheck_shutdown_timeout(HinemosPropertyBean.numeric(15000L)),
	http_proxy_host(HinemosPropertyBean.string()),
	http_proxy_ignorehosts(HinemosPropertyBean.string()),
	http_proxy_password(HinemosPropertyBean.string()),
	http_proxy_port(HinemosPropertyBean.numeric()),
	http_proxy_user(HinemosPropertyBean.string()),
	hub_binary_search_max_count(HinemosPropertyBean.numeric(1000L)),
	hub_binary_search_timeout(HinemosPropertyBean.numeric(15000L)),
	hub_fluentd_proxy_host(HinemosPropertyBean.string()),
	hub_fluentd_proxy_ignorehosts(HinemosPropertyBean.string()),
	hub_fluentd_proxy_password(HinemosPropertyBean.string()),
	hub_fluentd_proxy_port(HinemosPropertyBean.numeric()),
	hub_fluentd_proxy_user(HinemosPropertyBean.string()),
	hub_search_switch_join(HinemosPropertyBean.bool(false)),
	hub_search_timeout(HinemosPropertyBean.numeric(15000L)),
	hub_transfer_batch_basetime(HinemosPropertyBean.string("00:00")),
	hub_transfer_delay_interval(HinemosPropertyBean.string("0 0 0 * * ? *")),
	hub_transfer_max_try_count(HinemosPropertyBean.numeric(5L)),
	hub_transfer_fetch_size(HinemosPropertyBean.numeric(10000L)),
	infra_check_timeout(HinemosPropertyBean.numeric(Long.valueOf(50 * 1000))),
	infra_checkcommand_returnvalue_default(HinemosPropertyBean.numeric(1L)),
	infra_command_md5(HinemosPropertyBean.string("md5sum \"%s\" | awk '{print $1}'")),
	infra_management_access_input_type(HinemosPropertyBean.numeric(Long.valueOf(InfraNodeInputConstant.TYPE_NODE_PARAM))),
	infra_management_file_module_return_failure(HinemosPropertyBean.numeric(-1L)),
	infra_management_file_module_return_success(HinemosPropertyBean.numeric(0L)),
	infra_management_module_maxcount(HinemosPropertyBean.numeric(256L)),
	infra_max_file_size(HinemosPropertyBean.numeric(Long.valueOf(1024 * 1024 * 64))),
	infra_run_thread(HinemosPropertyBean.numeric(16L)),
	infra_run_timeout(HinemosPropertyBean.numeric(Long.valueOf(5 * 60 * 1000))),
	infra_transfer_agent_password(HinemosPropertyBean.string("HINEMOS_AGENT")),
	infra_transfer_filesize(HinemosPropertyBean.numeric(20481L)),
	infra_transfer_winrm_url(HinemosPropertyBean.string("")),
	infra_winrm_ssl_trustall(HinemosPropertyBean.bool(true)),
	internal_command( HinemosPropertyBean.bool(false)),
	internal_command_priority(HinemosPropertyBean.string("info")),
	internal_command_timeout(HinemosPropertyBean.numeric(15000L)),
	internal_event(HinemosPropertyBean.bool(true)),
	internal_event_priority(HinemosPropertyBean.string("info")),
	internal_file(HinemosPropertyBean.bool(true)),
	internal_file_priority(HinemosPropertyBean.string("info")),
	internal_mail(HinemosPropertyBean.bool(false)),
	internal_mail_address(HinemosPropertyBean.string("user1@host.domain,user2@host.domain")),
	internal_mail_priority(HinemosPropertyBean.string("info")),
	internal_syslog(HinemosPropertyBean.bool(false)),
	internal_syslog_facility(HinemosPropertyBean.string("daemon")),
	internal_syslog_host(HinemosPropertyBean.string("192.168.1.1,192.168.1.2")),
	internal_syslog_port(HinemosPropertyBean.numeric(514L)),
	internal_syslog_priority(HinemosPropertyBean.string("info")),
	internal_syslog_severity(HinemosPropertyBean.string("alert")),
	job_approval_page_link(HinemosPropertyBean.string("http://192.168.1.1/#approval?LoginUrl=http://192.168.1.1:8080/HinemosWS/")),
	job_end_delay_change_mount_lower_limit(HinemosPropertyBean.numeric(5L)),
	job_hulft_mode(HinemosPropertyBean.bool(false)),
	job_hulft_script_dir_linux(HinemosPropertyBean.string(CreateHulftJob.SCRIPT_DIR_LINUX)),
	job_hulft_script_dir_windows(HinemosPropertyBean.string(CreateHulftJob.SCRIPT_DIR_WIN)),
	job_message_max_length(HinemosPropertyBean.numeric(2048L)),
	job_monitor_thread_pool_size(HinemosPropertyBean.numeric(5L)),
	job_open_forward_file_job(HinemosPropertyBean.bool(false)),
	job_param_disable(HinemosPropertyBean.string("")),
	job_retry_interval(HinemosPropertyBean.numeric(Long.valueOf(10 * 1000))),
	job_schedule_plan_max(HinemosPropertyBean.numeric(2030L)),
	job_script_maxsize(HinemosPropertyBean.numeric(8192L)),
	job_session_change_data_analysys_count(HinemosPropertyBean.numeric(30L)),
	job_session_change_data_analysys_range(HinemosPropertyBean.numeric(43200L)),
	jobmap_icon_id_default_approvaljob(HinemosPropertyBean.string("APPROVALJOB_DEFAULT")),
	jobmap_icon_id_default_filejob(HinemosPropertyBean.string("FILEJOB_DEFAULT")),
	jobmap_icon_id_default_job(HinemosPropertyBean.string("JOB_DEFAULT")),
	jobmap_icon_id_default_jobnet(HinemosPropertyBean.string("JOBNET_DEFAULT")),
	jobmap_icon_id_default_monitorjob(HinemosPropertyBean.string("MONITORJOB_DEFAULT")),
	mail_$_allow8bitmime(HinemosPropertyBean.bool()),
	mail_$_auth(HinemosPropertyBean.bool()),
	mail_$_auth_digest_md5_disable(HinemosPropertyBean.bool()),
	mail_$_auth_login_disable(HinemosPropertyBean.bool()),
	mail_$_auth_mechanisms(HinemosPropertyBean.string()),
	mail_$_auth_ntlm_disable(HinemosPropertyBean.bool()),
	mail_$_auth_ntlm_domain(HinemosPropertyBean.string()),
	mail_$_auth_ntlm_flags(HinemosPropertyBean.numeric()),
	mail_$_auth_plain_disable(HinemosPropertyBean.bool()),
	mail_$_connectiontimeout(HinemosPropertyBean.numeric()),
	mail_$_dsn_notify(HinemosPropertyBean.string()),
	mail_$_dsn_ret(HinemosPropertyBean.string()),
	mail_$_ehlo(HinemosPropertyBean.bool()),
	mail_$_from(HinemosPropertyBean.string()),
	mail_$_host(HinemosPropertyBean.string()),
	mail_$_localaddress(HinemosPropertyBean.string()),
	mail_$_localhost(HinemosPropertyBean.string()),
	mail_$_localport(HinemosPropertyBean.numeric()),
	mail_$_mailextension(HinemosPropertyBean.string()),
	mail_$_noop_strict(HinemosPropertyBean.bool()),
	mail_$_port(HinemosPropertyBean.numeric()),
	mail_$_quitwait(HinemosPropertyBean.bool()),
	mail_$_reportsuccess(HinemosPropertyBean.bool()),
	mail_$_sasl_authorizationid(HinemosPropertyBean.string()),
	mail_$_sasl_enable(HinemosPropertyBean.bool()),
	mail_$_sasl_mechanisms(HinemosPropertyBean.string()),
	mail_$_sasl_realm(HinemosPropertyBean.string()),
	mail_$_sasl_usecanonicalhostname(HinemosPropertyBean.bool()),
	mail_$_sendpartial(HinemosPropertyBean.bool()),
	mail_$_socketFactory_class(HinemosPropertyBean.string()),
	mail_$_socketFactory_fallback(HinemosPropertyBean.bool()),
	mail_$_socketFactory_port(HinemosPropertyBean.numeric()),
	mail_$_socks_host(HinemosPropertyBean.string()),
	mail_$_socks_port(HinemosPropertyBean.string()),
	mail_$_starttls_enable(HinemosPropertyBean.bool()),
	mail_$_starttls_required(HinemosPropertyBean.bool()),
	mail_$_submitter(HinemosPropertyBean.string()),
	mail_$_timeout(HinemosPropertyBean.numeric()),
	mail_$_user(HinemosPropertyBean.string()),
	mail_$_userset(HinemosPropertyBean.bool()),
	mail_$_writetimeout(HinemosPropertyBean.numeric()),
	mail_charset_address(HinemosPropertyBean.string("UTF-8")),
	mail_charset_content(HinemosPropertyBean.string("UTF-8")),
	mail_charset_subject(HinemosPropertyBean.string("UTF-8")),
	mail_debug(HinemosPropertyBean.bool(false)),
	mail_errors_to_address(HinemosPropertyBean.string("admin@hinemos.com")),
	mail_from_address(HinemosPropertyBean.string("admin@hinemos.com")),
	mail_from_personal_name(HinemosPropertyBean.string("Hinemos Admin")),
	mail_native_to_ascii(HinemosPropertyBean.bool(false)),
	mail_reply_personal_name(HinemosPropertyBean.string("Hinemos Admin")),
	mail_reply_to_address(HinemosPropertyBean.string("admin@hinemos.com")),
	mail_smtp_ssl_checkserveridentity(HinemosPropertyBean.bool()),
	mail_smtp_ssl_ciphersuites(HinemosPropertyBean.string()),
	mail_smtp_ssl_enable(HinemosPropertyBean.bool()),
	mail_smtp_ssl_protocols(HinemosPropertyBean.string()),
	mail_smtp_ssl_socketFactory_class(HinemosPropertyBean.string()),
	mail_smtp_ssl_socketFactory_port(HinemosPropertyBean.numeric()),
	mail_smtp_ssl_trust(HinemosPropertyBean.string()),
	mail_store_protocol(HinemosPropertyBean.string("pop3")),
	mail_transport_password(HinemosPropertyBean.string("password")),
	mail_transport_protocol(HinemosPropertyBean.string("smtp")),
	mail_transport_tries(HinemosPropertyBean.numeric(1L)),
	mail_transport_tries_interval(HinemosPropertyBean.numeric(10000L)),
	mail_transport_user(HinemosPropertyBean.string("nobody")),
	maintenance_query_timeout(HinemosPropertyBean.numeric(0L)),
	monitor_agent_valid_multi(HinemosPropertyBean.numeric(2L)),
	monitor_agent_valid_plus(HinemosPropertyBean.numeric(Long.valueOf(10 * 1000))),
	monitor_change_lower_limit(HinemosPropertyBean.numeric(5L)),
	monitor_common_report_event_bom(HinemosPropertyBean.bool(true)),
	monitor_common_report_event_count(HinemosPropertyBean.numeric(2000L)),
	monitor_common_report_event_format(HinemosPropertyBean.string("yyyy/MM/dd HH:mm:ss")),
	monitor_common_report_event_separator(HinemosPropertyBean.string(",")),
	monitor_common_thread_pool(HinemosPropertyBean.numeric(10L)),
	monitor_correlation_lower_limit(HinemosPropertyBean.numeric(5L)),
	monitor_custom_valid_second(HinemosPropertyBean.numeric(15L)),
	monitor_customtrap_charset(HinemosPropertyBean.string("UTF-8")),
	monitor_customtrap_http_backlog_size(HinemosPropertyBean.numeric(0L)),
	monitor_customtrap_http_pool_size(HinemosPropertyBean.numeric(1L)),
	monitor_customtrap_http_queue_size(HinemosPropertyBean.numeric(Long.valueOf(15 * 60 * 30))),
	monitor_Customtrap_RecentData_Map_size(HinemosPropertyBean.numeric(256L)),
	monitor_customtrap_stats_interval(HinemosPropertyBean.numeric(100L)),
	monitor_customtrap_url(HinemosPropertyBean.string("http://0.0.0.0:8082/")),
	monitor_http_content_type(HinemosPropertyBean.string("text")),
	monitor_http_post_charset(HinemosPropertyBean.string("UTF-8")),
	monitor_http_scenario_disable_proxy_cache(HinemosPropertyBean.bool(true)),
	monitor_http_ssl_trustall(HinemosPropertyBean.bool(true)),
	monitor_integration_search_timeout(HinemosPropertyBean.numeric(15000L)),
	monitor_jmx_rmi_format(HinemosPropertyBean.string("service:jmx:rmi:///jndi/rmi://%s:%d/jmxrmi")),
	monitor_jmx_valid_second(HinemosPropertyBean.numeric(15L)),
	monitor_log_line_max_length(HinemosPropertyBean.numeric(256L)),
	monitor_logcount_search_timeout(HinemosPropertyBean.numeric(15000L)),
	monitor_node_delay_fix(HinemosPropertyBean.bool(false)),
	monitor_ping_fping_bytes(HinemosPropertyBean.numeric(56L)),
	monitor_ping_fping_count(HinemosPropertyBean.numeric(1L)),
	monitor_ping_fping_enable(HinemosPropertyBean.bool(true)),
	monitor_ping_fping_interval(HinemosPropertyBean.numeric(1000L)),
	monitor_ping_fping_timeout(HinemosPropertyBean.numeric(1000L)),
	monitor_poller_snmp_bulk_maxrepetitions(HinemosPropertyBean.numeric(10L)),
	monitor_poller_snmp_bulk_nonrepeaters(HinemosPropertyBean.numeric(0L)),
	monitor_poller_snmp_max_retry(HinemosPropertyBean.numeric(3L)),
	monitor_poller_snmp_not_v3_snmp_pool_size(HinemosPropertyBean.numeric(32L)),
	monitor_port_protocol_dns(HinemosPropertyBean.string("localhost")),
	monitor_prediction_lower_limit(HinemosPropertyBean.numeric(5L)),
	monitor_process_collect_initdelay_second(HinemosPropertyBean.numeric(60L)),
	monitor_process_details_display(HinemosPropertyBean.bool(false)),
	monitor_process_start_second(HinemosPropertyBean.numeric(30L)),
	monitor_process_valid_second(HinemosPropertyBean.numeric(50L)),
	monitor_resource_delete_label(HinemosPropertyBean.bool(true)),
	monitor_resource_label_replace(HinemosPropertyBean.string(" Label:\\S*  Serial Number .*")),
	monitor_snmp_valid_second(HinemosPropertyBean.numeric(15L)),
	monitor_snmptrap_charset(HinemosPropertyBean.string("UTF-8")),
	monitor_snmptrap_filter_queue_size(HinemosPropertyBean.numeric(Long.valueOf(15 * 60 * 30))),
	monitor_snmptrap_filter_thread_size(HinemosPropertyBean.numeric(1L)),
	monitor_snmptrap_listen_address(HinemosPropertyBean.string("0.0.0.0")),
	monitor_snmptrap_listen_port(HinemosPropertyBean.numeric(162L)),
	monitor_snmptrap_org_message_community(HinemosPropertyBean.bool(true)),
	monitor_snmptrap_org_message_varbind(HinemosPropertyBean.bool(true)),
	monitor_snmptrap_stats_interval(HinemosPropertyBean.numeric(100L)),
	monitor_snmptrap_v3_auth_password(HinemosPropertyBean.string("authPassword")),
	monitor_snmptrap_v3_auth_protocol(HinemosPropertyBean.string("MD5")),
	monitor_snmptrap_v3_priv_password(HinemosPropertyBean.string("privPassword")),
	monitor_snmptrap_v3_priv_protocol(HinemosPropertyBean.string("DES")),
	monitor_snmptrap_v3_security_level(HinemosPropertyBean.string("noauth_nopriv")),
	monitor_snmptrap_v3_user(HinemosPropertyBean.string("hinemos")),
	monitor_sql_jdbc_driver(HinemosPropertyBean.numeric(3L)),
	monitor_sql_jdbc_driver_classname_$(HinemosPropertyBean.string()),
	monitor_sql_jdbc_driver_logintimeout_$(HinemosPropertyBean.numeric()),
	monitor_sql_jdbc_driver_name_$(HinemosPropertyBean.string()),
	monitor_sql_jdbc_driver_properties_$(HinemosPropertyBean.string()),
	monitor_systemlog_filter_queue_size(HinemosPropertyBean.numeric(Long.valueOf(15 * 60 * 30))),
	monitor_systemlog_filter_thread_size(HinemosPropertyBean.numeric(1L)),
	monitor_systemlog_listen_address(HinemosPropertyBean.string("0.0.0.0")),
	monitor_systemlog_listen_port(HinemosPropertyBean.numeric(514L)),
	monitor_systemlog_listen_tcp(HinemosPropertyBean.bool(true)),
	monitor_systemlog_listen_udp(HinemosPropertyBean.bool(true)),
	monitor_systemlog_period_hour(HinemosPropertyBean.numeric(Long.valueOf(SyslogMessage.SYSLOG_DEFAULT_PERIOD_HOUR))),
	monitor_systemlog_receiverid(HinemosPropertyBean.string(System.getProperty("hinemos.manager.nodename"))),
	monitor_systemlog_shutdown_timeout(HinemosPropertyBean.numeric(60000L)),
	monitor_systemlog_stats_interval(HinemosPropertyBean.numeric(1000L)),
	monitor_systemlog_split_code(HinemosPropertyBean.string("10")),
	monitor_systemlog_message_charset(HinemosPropertyBean.string("UTF-8")),
	monitor_systemlog_header_charset(HinemosPropertyBean.string("ascii")),
	monitor_systemlog_receive_tcp_read_max_size(HinemosPropertyBean.string("4096")),
	monitor_systemlog_receive_tcp_read_timeout(HinemosPropertyBean.numeric(1000*10L)),
	monitor_systemlog_receive_udp_buffer(HinemosPropertyBean.numeric()),
	monitor_systemlog_worker_thread_max_size(HinemosPropertyBean.numeric(1000L)),
	monitor_sytemslog_worker_thread_keepalive_timeout(HinemosPropertyBean.numeric(5000L)),
	monitor_winservice_ssl_trustall(HinemosPropertyBean.bool(true)),
	nodemap_ping_runcount(HinemosPropertyBean.numeric(Long.valueOf(PingRunCountConstant.TYPE_COUNT_01))),
	nodemap_ping_runinterval(HinemosPropertyBean.numeric(Long.valueOf(PingRunIntervalConstant.TYPE_SEC_02))),
	nodemap_ping_timeout(HinemosPropertyBean.numeric(Long.valueOf(PingRunIntervalConstant.TYPE_SEC_05))),
	nodemap_search_connection_thread(HinemosPropertyBean.numeric(4L)),
	notify_command_create_mode(HinemosPropertyBean.string("auto")),
	notify_command_thread_pool_count(HinemosPropertyBean.numeric(8L)),
	notify_commandsuccess_exit(HinemosPropertyBean.numeric(0L)),
	notify_date_format(HinemosPropertyBean.string("yyyy/MM/dd HH:mm:ss")),
	notify_event_cache_size(HinemosPropertyBean.numeric(10000L)),
	notify_event_diff(HinemosPropertyBean.bool(false)),
	notify_event_message_max_length(HinemosPropertyBean.numeric(255L)),
	notify_event_messageorg_max_length(HinemosPropertyBean.numeric(1024L)),
	notify_initial_count_max(HinemosPropertyBean.numeric(10L)),
	notify_locale(HinemosPropertyBean.string()),
	notify_log_escalate_manager_hostname(HinemosPropertyBean.string()),
	notify_log_escalate_manager_protocol(HinemosPropertyBean.string("udp")),
	notify_log_escalate_manager_retry_count(HinemosPropertyBean.numeric(1L)),
	notify_log_escalate_manager_retry_interval(HinemosPropertyBean.numeric(10000L)),
	notify_log_escalate_manager_tcp_timeout(HinemosPropertyBean.numeric(3000L)),
	notify_mode(HinemosPropertyBean.string("normal")),
	notify_remove_subkey_$(HinemosPropertyBean.bool()),
	notify_replace_after(HinemosPropertyBean.string("?")),
	notify_replace_before(HinemosPropertyBean.string("0")),
	performance_export_encode(HinemosPropertyBean.string("MS932")),
	performance_export_fetchsize(HinemosPropertyBean.numeric(1000L)),
	performance_export_line_separator(HinemosPropertyBean.string("CRLF")),
	repository_auto_device_find_log(HinemosPropertyBean.bool(false)),
	repository_auto_device_user(HinemosPropertyBean.string(UserIdConstant.HINEMOS)),
	repository_device_search_interval(HinemosPropertyBean.numeric(5L)),
	repository_device_search_prop_basic_agent(HinemosPropertyBean.bool(false)),
	repository_device_search_prop_basic_hardware(HinemosPropertyBean.bool(false)),
	repository_device_search_prop_basic_network(HinemosPropertyBean.bool(true)),
	repository_device_search_prop_basic_os(HinemosPropertyBean.bool(false)),
	repository_device_search_prop_device_cpu(HinemosPropertyBean.bool(true)),
	repository_device_search_prop_device_disk(HinemosPropertyBean.bool(true)),
	repository_device_search_prop_device_filesystem(HinemosPropertyBean.bool(true)),
	repository_device_search_prop_device_general(HinemosPropertyBean.bool(false)),
	repository_device_search_prop_device_memory(HinemosPropertyBean.bool(true)),
	repository_device_search_prop_device_nic(HinemosPropertyBean.bool(true)),
	repository_device_search_threadpool_size(HinemosPropertyBean.numeric(5L)),
	repository_device_search_verbose(HinemosPropertyBean.bool(false)),
	repository_node_search_delay(HinemosPropertyBean.numeric(10L)),
	repository_node_search_max_node(HinemosPropertyBean.numeric(256L)),
	repository_node_search_timeout(HinemosPropertyBean.numeric(Long.valueOf(50 * 1000))),
	repository_nodename_fqdn(HinemosPropertyBean.bool(false)),
	repository_restart_sleep(HinemosPropertyBean.numeric(RepositoryControllerBean.RESTART_AGENT_SLEEP_TIME)),
	repository_snmp_oid_contact(HinemosPropertyBean.string(".1.3.6.1.2.1.1.4.0")),
	repository_snmp_oid_cpu_index(HinemosPropertyBean.string(".1.3.6.1.2.1.25.3.3.1.2")),
	repository_snmp_oid_descr(HinemosPropertyBean.string(".1.3.6.1.2.1.1.1.0")),
	repository_snmp_oid_disk_index(HinemosPropertyBean.string(".1.3.6.1.4.1.2021.13.15.1.1.1")),
	repository_snmp_oid_disk_io_read(HinemosPropertyBean.string(".1.3.6.1.4.1.2021.13.15.1.1.5")),
	repository_snmp_oid_disk_io_write(HinemosPropertyBean.string(".1.3.6.1.4.1.2021.13.15.1.1.6")),
	repository_snmp_oid_disk_ion_read(HinemosPropertyBean.string(".1.3.6.1.4.1.2021.13.15.1.1.3")),
	repository_snmp_oid_disk_ion_write(HinemosPropertyBean.string(".1.3.6.1.4.1.2021.13.15.1.1.4")),
	repository_snmp_oid_disk_name(HinemosPropertyBean.string(".1.3.6.1.4.1.2021.13.15.1.1.2")),
	repository_snmp_oid_filesystem_index(HinemosPropertyBean.string(".1.3.6.1.2.1.25.2.3.1.1")),
	repository_snmp_oid_filesystem_name(HinemosPropertyBean.string(".1.3.6.1.2.1.25.2.3.1.3")),
	repository_snmp_oid_filesystem_size(HinemosPropertyBean.string(".1.3.6.1.2.1.25.2.3.1.5")),
	repository_snmp_oid_filesystem_type(HinemosPropertyBean.string(".1.3.6.1.2.1.25.2.3.1.2")),
	repository_snmp_oid_name(HinemosPropertyBean.string(".1.3.6.1.2.1.1.5.0")),
	repository_snmp_oid_nic_in_octet(HinemosPropertyBean.string(".1.3.6.1.2.1.2.2.1.10")),
	repository_snmp_oid_nic_index(HinemosPropertyBean.string(".1.3.6.1.2.1.2.2.1.1")),
	repository_snmp_oid_nic_ipv4_address(HinemosPropertyBean.string(".1.3.6.1.2.1.4.34.1.3.1.4")),
	repository_snmp_oid_nic_ipv4_address_type(HinemosPropertyBean.string(".1.3.6.1.2.1.4.34.1.4.1.4")),
	repository_snmp_oid_nic_ipv6_address(HinemosPropertyBean.string(".1.3.6.1.2.1.4.34.1.3.2.16")),
	repository_snmp_oid_nic_ipv6_address_type(HinemosPropertyBean.string(".1.3.6.1.2.1.4.34.1.4.2.16")),
	repository_snmp_oid_nic_mac_address(HinemosPropertyBean.string(".1.3.6.1.2.1.2.2.1.6")),
	repository_snmp_oid_nic_name(HinemosPropertyBean.string(".1.3.6.1.2.1.2.2.1.2")),
	repository_snmp_oid_nic_out_octet(HinemosPropertyBean.string(".1.3.6.1.2.1.2.2.1.16")),
	repository_snmp_retry(HinemosPropertyBean.numeric(1L)),
	repository_snmp_timeout(HinemosPropertyBean.numeric(5000L)),
	scheduler_dbms_misfireThreshold(HinemosPropertyBean.numeric(3600000L)),
	scheduler_dbms_threadPool_size(HinemosPropertyBean.numeric(8L)),
	scheduler_job_cron(HinemosPropertyBean.string("0 */1 * * * ? *")),
	scheduler_monitor_cron(HinemosPropertyBean.string("0 */5 * * * ? *")),
	scheduler_monitor_status_cron(HinemosPropertyBean.string("50 3/10 * * * ? *")),
	scheduler_ram_misfireThreshold(HinemosPropertyBean.numeric(3600000L)),
	scheduler_ram_threadPool_size(HinemosPropertyBean.numeric(32L)),
	scheduler_repository_cron(HinemosPropertyBean.string("40 */1 * * * ? *")),
	selfcheck_alert_threshold(HinemosPropertyBean.numeric(3L)),
	selfcheck_interval(HinemosPropertyBean.numeric(150L)),
	selfcheck_monitoring_asynctask_queue(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_asynctask_queue_list(HinemosPropertyBean.string("NotifyStatusTaskFactory:10000,NotifyEventTaskFactory:10000,NotifyMailTaskFactory:10000,NotifyCommandTaskFactory:10000,NotifyLogEscalationTaskFactory:10000,NotifyJobTaskFactory:10000,CreateJobSessionTaskFactory:100,NotifyInfraTaskFactory:10000")),
	selfcheck_monitoring_db(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_db_connection_count(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_db_connection_count_threshold(HinemosPropertyBean.numeric(80L)),
	selfcheck_monitoring_dbsize(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_dbsize_threshold(HinemosPropertyBean.numeric(10240L)),
	selfcheck_monitoring_dbtran(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_dbtran_interval(HinemosPropertyBean.numeric(86400L)),
	selfcheck_monitoring_filesystem_usage(HinemosPropertyBean.bool(false)),
	selfcheck_monitoring_filesystem_usage_list(HinemosPropertyBean.string("/:50")),
	selfcheck_monitoring_job_runningsession(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_job_runningsession_threshold(HinemosPropertyBean.numeric(1000L)),
	selfcheck_monitoring_jvm_freeheap(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_jvm_freeheap_threshold(HinemosPropertyBean.numeric(32L)),
	selfcheck_monitoring_scheduler_delay(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_scheduler_delay_threshold(HinemosPropertyBean.numeric(300L)),
	selfcheck_monitoring_snmptrap_queue(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_snmptrap_queue_threshold(HinemosPropertyBean.numeric(10000L)),
	selfcheck_monitoring_swapout(HinemosPropertyBean.bool(false)),
	selfcheck_monitoring_systemlog_queue(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_systemlog_queue_threshold(HinemosPropertyBean.numeric(10000L)),
	selfcheck_monitoring_table_size(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_table_size_list(HinemosPropertyBean.string("log.cc_event_log:20480:MBYTE,log.cc_collect_data_raw:20480:MBYTE,log.cc_collect_data_string:40960:MBYTE,log.cc_job_session:100000:COUNT")),
	selfcheck_monitoring_thread_activity(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_thread_activity_threshold(HinemosPropertyBean.numeric(300L)),
	selfcheck_monitoring_ws_agent_queue(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_ws_agent_queue_threshold(HinemosPropertyBean.numeric(960L)),
	selfcheck_monitoring_ws_agentbinary_queue(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_ws_agentbinary_queue_threshold(HinemosPropertyBean.numeric(960L)),
	selfcheck_monitoring_ws_agenthub_queue(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_ws_agenthub_queue_threshold(HinemosPropertyBean.numeric(960L)),
	selfcheck_monitoring_ws_queue(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_ws_queue_threshold(HinemosPropertyBean.numeric(240L)),
	selfcheck_snmp_community(HinemosPropertyBean.string("public")),
	selfcheck_snmp_port(HinemosPropertyBean.numeric(161L)),
	selfcheck_snmp_retries(HinemosPropertyBean.numeric(3L)),
	selfcheck_snmp_timeout(HinemosPropertyBean.numeric(3000L)),
	selfcheck_snmp_version(HinemosPropertyBean.string(SnmpVersionConstant.STRING_V2)),
	selfcheck_startup_delay(HinemosPropertyBean.numeric(90L)),
	selfcheck_threadpool_size(HinemosPropertyBean.numeric(4L)),
	system_sun_rmi_transport_tcp_responseTimeout(HinemosPropertyBean.numeric(Long.valueOf(10 * 1000))),
	ws_agent_address(HinemosPropertyBean.string("http://0.0.0.0:8081")),
	ws_agent_queue_size(HinemosPropertyBean.numeric(1200L)),
	ws_agent_shutdown_timeout(HinemosPropertyBean.numeric(60000L)),
	ws_agent_threadpool_size(HinemosPropertyBean.numeric(8L)),
	ws_client_address(HinemosPropertyBean.string("http://0.0.0.0:8080")),
	ws_client_shutdown_timeout(HinemosPropertyBean.numeric(10000L)),
	ws_client_threadpool_size(HinemosPropertyBean.numeric(8L)),
	ws_https_keystore_password(HinemosPropertyBean.string("hinemos")),
	ws_https_keystore_type(HinemosPropertyBean.string("PKCS12")),
	ws_https_protocol(HinemosPropertyBean.string("TLS")),
	worker_$_factoryclass(HinemosPropertyBean.string()),
	worker_$_thread_size(HinemosPropertyBean.numeric()),
	worker_$_queue_size(HinemosPropertyBean.numeric()),
	worker_$_shutdown_timeout(HinemosPropertyBean.numeric()),
	worker_list(HinemosPropertyBean.string(
			AsyncWorkerPlugin.NOTIFY_STATUS_TASK_FACTORY +"," + 
			AsyncWorkerPlugin.NOTIFY_EVENT_TASK_FACTORY +"," + 
			AsyncWorkerPlugin.NOTIFY_MAIL_TASK_FACTORY +"," + 
			AsyncWorkerPlugin.NOTIFY_COMMAND_TASK_FACTORY +"," + 
			AsyncWorkerPlugin.NOTIFY_LOG_ESCALATION_TASK_FACTORY +"," + 
			AsyncWorkerPlugin.NOTIFY_JOB_TASK_FACTORY +"," + 
			AsyncWorkerPlugin.CREATE_JOB_SESSION_TASK_FACTORY +"," + 
			AsyncWorkerPlugin.NOTIFY_INFRA_TASK_FACTORY)),
	worker_async_task_persist_monitor_agent(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_custom(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_http(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_performance(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_ping(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_port(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_process(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_snmptrap(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_snmp(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_sql(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_syslog(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_logfile(HinemosPropertyBean.bool(true)),
	worker_async_task_persist_monitor_logcount(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_binaryfile(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_packetcapture(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_job(HinemosPropertyBean.bool(true)),
	worker_async_task_persist_maintenance(HinemosPropertyBean.bool(true)),
	worker_async_task_persist_monitor_winevent(HinemosPropertyBean.bool(true)),
	worker_async_task_persist_monitor_customtrap(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_correlation(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_integration(HinemosPropertyBean.bool(false)),
	ws_queue_size(HinemosPropertyBean.numeric(300L)),

	/* xCloud用プロパティ */
	xcloud_env_path_python(HinemosPropertyBean.string("")),
	xcloud_agent_connection_count(HinemosPropertyBean.numeric(30L)),
	xcloud_agent_connection_interval(HinemosPropertyBean.numeric(10000L)),
	xcloud_autoregist_node_entity(HinemosPropertyBean.bool(true)),
	xcloud_autodelete_node_entity(HinemosPropertyBean.bool(false)),
	xcloud_autoregist_node_instance(HinemosPropertyBean.bool(true)),
	xcloud_autodelete_node_instance(HinemosPropertyBean.bool(false)),
	xcloud_autodelete_instance(HinemosPropertyBean.bool(true)),
	xcloud_instance_snapshot_count_max(HinemosPropertyBean.numeric(5L)),
	xcloud_ipaddress_cidr(HinemosPropertyBean.string("10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16")),
	xcloud_ipaddress_notavailable(HinemosPropertyBean.string("169.254.0.0")),
	xcloud_agent_connection_enable(HinemosPropertyBean.bool(true)),
	xcloud_node_property_cloud_service_update(HinemosPropertyBean.bool(true)),
	xcloud_node_property_platformfamily_update(HinemosPropertyBean.bool(true)),
	xcloud_node_property_subplatformfamily_update(HinemosPropertyBean.bool(true)),
	xcloud_node_property_nodename_update(HinemosPropertyBean.bool(true)),
	xcloud_node_property_cloud_scope_update(HinemosPropertyBean.bool(true)),
	xcloud_node_property_cloud_resourcename_update(HinemosPropertyBean.bool(true)),
	xcloud_node_property_cloud_resourcetype_update(HinemosPropertyBean.bool(true)),
	xcloud_node_property_cloud_resourceid_update(HinemosPropertyBean.bool(true)),
	xcloud_node_property_cloud_location_update(HinemosPropertyBean.bool(true)),
	xcloud_node_property_cloud_ipaddress_update(HinemosPropertyBean.bool(true)),
	xcloud_node_property_cloud_validflag_update(HinemosPropertyBean.bool(true)),
	xcloud_node_property_cloud_validflag_excludestates(HinemosPropertyBean.string("")),
	xcloud_node_property_nic_update(HinemosPropertyBean.bool(true)),
	xcloud_autoupdate_agent(HinemosPropertyBean.bool(false)),
	xcloud_storage_snapshot_count_max(HinemosPropertyBean.numeric(5L)),
	xcloud_billing_detail_collect_time(HinemosPropertyBean.string("0 0 2 * * ?")),
	xcloud_autoupdate_node(HinemosPropertyBean.bool(true)),
	xcloud_registcheck_interval(HinemosPropertyBean.numeric(10000L)),
	xcloud_registcheck_count(HinemosPropertyBean.numeric(30L)),
	xcloud_autoupdate_storage_enable(HinemosPropertyBean.bool(true)),
	xcloud_autoupdate_storage_snapshot_enable(HinemosPropertyBean.bool(true)),
	xcloud_autoupdate_instance_snapshot_enable(HinemosPropertyBean.bool(true)),
	xcloud_autoupdate_interval(HinemosPropertyBean.string("0 */10 * * * ?")),
	xcloud_platform_service_monitor_interval(HinemosPropertyBean.string("0 */10 * * * ?")),
	xcloud_node_property_node_variablename(HinemosPropertyBean.string("")),
	xcloud_node_property_node_variablevalue(HinemosPropertyBean.string("")),
	xcloud_node_property_agent_awakeport(HinemosPropertyBean.numeric(24005L)),
	xcloud_node_property_job_priority(HinemosPropertyBean.numeric(16L)),
	xcloud_node_property_job_multiplicity(HinemosPropertyBean.numeric(0L)),
	xcloud_node_property_snmp_user(HinemosPropertyBean.string("root")),
	xcloud_node_property_snmp_port(HinemosPropertyBean.numeric(161L)),
	xcloud_node_property_snmp_community(HinemosPropertyBean.string("public")),
	xcloud_node_property_snmp_version(HinemosPropertyBean.string(SnmpVersionConstant.STRING_V2)),
	xcloud_node_property_snmp_securitylevel(HinemosPropertyBean.string("noauth_nopriv")),
	xcloud_node_property_snmp_timeout(HinemosPropertyBean.numeric(5000L)),
	xcloud_node_property_snmp_retries(HinemosPropertyBean.numeric(3L)),
	xcloud_node_property_wbem_user(HinemosPropertyBean.string("root")),
	xcloud_node_property_wbem_userpassword(HinemosPropertyBean.string("")),
	xcloud_node_property_wbem_port(HinemosPropertyBean.numeric(5988L)),
	xcloud_node_property_wbem_protocol(HinemosPropertyBean.string("http")),
	xcloud_node_property_wbem_timeout(HinemosPropertyBean.numeric(5000L)),
	xcloud_node_property_wbem_retries(HinemosPropertyBean.numeric(3L)),
	xcloud_node_property_ipmi_ipaddress(HinemosPropertyBean.string("")),
	xcloud_node_property_ipmi_port(HinemosPropertyBean.numeric(0L)),
	xcloud_node_property_ipmi_user(HinemosPropertyBean.string("")),
	xcloud_node_property_ipmi_userpassword(HinemosPropertyBean.string("")),
	xcloud_node_property_ipmi_timeout(HinemosPropertyBean.numeric(5000L)),
	xcloud_node_property_ipmi_retries(HinemosPropertyBean.numeric(3L)),
	xcloud_node_property_ipmi_protocol(HinemosPropertyBean.string("RMCP+")),
	xcloud_node_property_ipmi_level(HinemosPropertyBean.string("")),
	xcloud_node_property_winrm_user(HinemosPropertyBean.string("")),
	xcloud_node_property_winrm_userpassword(HinemosPropertyBean.string("")),
	xcloud_node_property_winrm_version(HinemosPropertyBean.string("2.0")),
	xcloud_node_property_winrm_port(HinemosPropertyBean.numeric(5985L)),
	xcloud_node_property_winrm_protocol(HinemosPropertyBean.string("http")),
	xcloud_node_property_winrm_timeout(HinemosPropertyBean.numeric(5000L)),
	xcloud_node_property_winrm_retries(HinemosPropertyBean.numeric(3L)),
	xcloud_node_property_ssh_user(HinemosPropertyBean.string("root")),
	xcloud_node_property_ssh_userpassword(HinemosPropertyBean.string("")),
	xcloud_node_property_ssh_privkey_path(HinemosPropertyBean.string("")),
	xcloud_node_property_ssh_privkey_passphrase(HinemosPropertyBean.string("")),
	xcloud_node_property_ssh_port(HinemosPropertyBean.numeric(22L)),
	xcloud_node_property_ssh_timeout(HinemosPropertyBean.numeric(50000L)),
	xcloud_node_property_administrator(HinemosPropertyBean.string("")),
	xcloud_node_property_contact(HinemosPropertyBean.string("")),
	xcloud_assign_to_multiple_scope(HinemosPropertyBean.bool(false)),
	xcloud_internal_thread_admin_user(HinemosPropertyBean.string("hinemos")),
	
	/* inquiry用プロパティ */
	inquiry_max_id_number(HinemosPropertyBean.numeric(0L)),
	inquiry_displayname_$(HinemosPropertyBean.string()),
	inquiry_command_$(HinemosPropertyBean.string()),
	inquiry_file_$(HinemosPropertyBean.string());
	;

	// Hinemosプロパティ情報
	private final HinemosPropertyBean bean;

	/**
	 * コンストラクタ
	 * @param bean Hinemosプロパティ情報
	 */
	private HinemosPropertyCommon(HinemosPropertyBean bean) {
		this.bean = bean;
	}

	/**
	 * Hinemosプロパティ情報取得
	 * 
	 * @return Hinemosプロパティ情報
	 */
	@Override
	public HinemosPropertyBean getBean() {
		return this.bean;
	}

	/**
	 * キー値変換
	 * 名前を"_"から"."に変換
	 * $は置換文字列に変換
	 * 例）　COMMON_$_OFFSET、置換文字列"time" → common.time.offset
	 * 
	 * @param replaceStr 置換文字列
	 * @return 変換後のキー
	 */
	@Override
	public String getReplaceKey(String replaceStr) {
		if (this == HinemosPropertyCommon.mail_$_auth_digest_md5_disable) {
			return "mail.$.auth.digest-md5.disable".replace("$", replaceStr);
		} else {
			return getKey().replace("$", replaceStr);
		}
	}

	/**
	 * Hinemosプロパティ（agent.connection.ipaddres）取得
	 * 存在しない場合はデフォルト値を使用
	 * ※デフォルト値がExceptionが発生するため、独自実装
	 * 
	 * @return Hinemosプロパティ値
	 */
	public String getAgentConnectionIpaddres() throws NullPointerException, UnknownHostException {
		HinemosPropertyBean bean = getBean();
		if (bean.getType() != HinemosPropertyTypeConstant.TYPE_STRING
				|| this != HinemosPropertyCommon.agent_connection_ipaddres) {
			throw new NullPointerException();
		}
		HinemosPropertyInfo info = new HinemosPropertyControllerBean().getHinemosPropertyInfo_None(getKey());
		if (info == null 
				|| info.getValueType() != HinemosPropertyTypeConstant.TYPE_STRING
				|| info.getValueString() == null 
				|| info.getValueString().isEmpty()) {
			return InetAddress.getLocalHost().getHostAddress();
		}
		return info.getValueString();
	}
}
