/*
 * Copyright (c) 2018 NTT DATA INTELLILINK Corporation. All rights reserved.
 *
 * Hinemos (http://www.hinemos.info/)
 *
 * See the LICENSE file for licensing information.
 */

package com.clustercontrol.commons.util;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.TimeZone;

import com.clustercontrol.accesscontrol.bean.UserIdConstant;
import com.clustercontrol.bean.HinemosModuleConstant;
import com.clustercontrol.bean.SnmpVersionConstant;
import com.clustercontrol.commons.bean.HinemosPropertyBean;
import com.clustercontrol.infra.bean.InfraNodeInputConstant;
import com.clustercontrol.jobmanagement.factory.CreateHulftJob;
import com.clustercontrol.maintenance.HinemosPropertyTypeConstant;
import com.clustercontrol.maintenance.model.HinemosPropertyInfo;
import com.clustercontrol.maintenance.session.HinemosPropertyControllerBean;
import com.clustercontrol.ping.bean.PingRunCountConstant;
import com.clustercontrol.ping.bean.PingRunIntervalConstant;
import com.clustercontrol.plugin.impl.AsyncWorkerPlugin;
import com.clustercontrol.systemlog.bean.SyslogMessage;

/**
 * HinemosPropertyのデフォルト値を格納するクラス<BR>
 *
 * @version 6.2.0
 * @since 6.1.0
 */
public enum HinemosPropertyCommon implements HinemosPropertyAbstract {
	access_authenticator_id(HinemosPropertyBean.string("")),
	access_authenticator_authtime(HinemosPropertyBean.numeric(10L)),
	access_user_password_hash(HinemosPropertyBean.string("SHA-256")),
	agent_connection_dnsname(HinemosPropertyBean.string("")),
	agent_connection_ipaddres(HinemosPropertyBean.string("")),
	agent_topic_setting_broadcast_awake_interval(HinemosPropertyBean.numeric(0L)),
	agent_topic_setting_broadcast_awake_amount(HinemosPropertyBean.numeric(1L)),
	agent_v62beta_md5s(HinemosPropertyBean.string(
			/* 20180912版 */ "0F5D8E6DEBB39751299529E9E35D2729," + 
			/* 20180810版 */ "45d547cb8cde483145513383573af6d3")),
	auto_register_node_incremental_loop(HinemosPropertyBean.numeric(100L)),
	auto_register_node_seaquential_digits(HinemosPropertyBean.numeric(4L)),
	auto_register_node_valid(HinemosPropertyBean.bool(false)),
	collect_graph_timeout_reporting(HinemosPropertyBean.numeric(50000L)),
	collect_graph_timeout(HinemosPropertyBean.numeric(50000L)),
	collect_logcount_thread_pool_size(HinemosPropertyBean.numeric(1L)),
	collect_logcount_timeout(HinemosPropertyBean.numeric(15000L)),
	common_agent_discovery_pingport(HinemosPropertyBean.numeric(24005L)),
	common_db_connectionpool_stats_threshold(HinemosPropertyBean.numeric(12L)),
	common_db_error_notify_suppression_time(HinemosPropertyBean.numeric(60000L)),
	common_invalid_char_replace(HinemosPropertyBean.bool(false)),
	common_invalid_char_replace_to(HinemosPropertyBean.string("?")),
	common_scheduler_startup_delay(HinemosPropertyBean.numeric(60L)),
	common_time_offset(HinemosPropertyBean.numeric(0L)),
	common_timezone(HinemosPropertyBean.numeric( Long.valueOf(TimeZone.getDefault().getRawOffset()))),
	dhcp_autoupdate_ipaddress_enable(HinemosPropertyBean.bool(true)),
	dhcp_autoupdate_ipaddress_cidr(HinemosPropertyBean.string("10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16")),
	dhcp_autoupdate_ipaddress_notavailable(HinemosPropertyBean.string("169.254.0.0")),
	dhcp_autoupdate_hostname_enable(HinemosPropertyBean.bool(true)),
	dhcp_autoupdate_hostname_cidr(HinemosPropertyBean.string("10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16")),
	hinemos_selfcheck_shutdown_timeout(HinemosPropertyBean.numeric(15000L)),
	http_proxy_host(HinemosPropertyBean.string()),
	http_proxy_ignorehosts(HinemosPropertyBean.string()),
	http_proxy_password(HinemosPropertyBean.string()),
	http_proxy_port(HinemosPropertyBean.numeric()),
	http_proxy_user(HinemosPropertyBean.string()),
	hub_binary_search_max_count(HinemosPropertyBean.numeric(1000L)),
	hub_binary_search_timeout(HinemosPropertyBean.numeric(15000L)),
	hub_fluentd_proxy_host(HinemosPropertyBean.string()),
	hub_fluentd_proxy_ignorehosts(HinemosPropertyBean.string()),
	hub_fluentd_proxy_password(HinemosPropertyBean.string()),
	hub_fluentd_proxy_port(HinemosPropertyBean.numeric()),
	hub_fluentd_proxy_user(HinemosPropertyBean.string()),
	hub_search_switch_join(HinemosPropertyBean.bool(false)),
	hub_search_timeout(HinemosPropertyBean.numeric(15000L)),
	hub_transfer_batch_basetime(HinemosPropertyBean.string("00:00")),
	hub_transfer_delay_interval(HinemosPropertyBean.string("0 0 0 * * ? *")),
	hub_transfer_max_try_count(HinemosPropertyBean.numeric(5L)),
	hub_transfer_fetch_size(HinemosPropertyBean.numeric(10000L)),
	hub_transfer_locale(HinemosPropertyBean.string("")),
	hub_transfer_fluentd_date_format(HinemosPropertyBean.string("")),
	infra_check_timeout(HinemosPropertyBean.numeric(Long.valueOf(50 * 1000))),
	infra_checkcommand_returnvalue_default(HinemosPropertyBean.numeric(1L)),
	infra_command_md5(HinemosPropertyBean.string("md5sum \"%s\" | awk '{print $1}'")),
	infra_management_access_input_type(HinemosPropertyBean.numeric(Long.valueOf(InfraNodeInputConstant.TYPE_NODE_PARAM))),
	infra_management_file_module_return_failure(HinemosPropertyBean.numeric(-1L)),
	infra_management_file_module_return_success(HinemosPropertyBean.numeric(0L)),
	infra_management_module_maxcount(HinemosPropertyBean.numeric(256L)),
	infra_max_file_size(HinemosPropertyBean.numeric(Long.valueOf(1024 * 1024 * 64))),
	infra_run_thread(HinemosPropertyBean.numeric(16L)),
	infra_run_timeout(HinemosPropertyBean.numeric(Long.valueOf(5 * 60 * 1000))),
	infra_transfer_agent_password(HinemosPropertyBean.string("HINEMOS_AGENT")),
	infra_transfer_filesize(HinemosPropertyBean.numeric(20481L)),
	infra_transfer_winrm_split_filesize(HinemosPropertyBean.numeric(1024L)),
	infra_transfer_winrm_url(HinemosPropertyBean.string("")),
	infra_replace_max_line_size(HinemosPropertyBean.numeric(Long.valueOf(1024 * 1024))),
	infra_winrm_ssl_trustall(HinemosPropertyBean.bool(true)),
	internal_command( HinemosPropertyBean.bool(false)),
	internal_command_priority(HinemosPropertyBean.string("info")),
	internal_command_timeout(HinemosPropertyBean.numeric(15000L)),
	internal_event(HinemosPropertyBean.bool(true)),
	internal_event_priority(HinemosPropertyBean.string("info")),
	internal_file(HinemosPropertyBean.bool(true)),
	internal_file_priority(HinemosPropertyBean.string("info")),
	internal_joblinkmes_forward_setting(HinemosPropertyBean.string("")),
	internal_joblinkmes_forward_priority(HinemosPropertyBean.string("info")),
	internal_joblinkmes_forward_retry_count(HinemosPropertyBean.numeric(0L)),
	internal_mail(HinemosPropertyBean.bool(false)),
	internal_mail_address(HinemosPropertyBean.string("user1@host.domain,user2@host.domain")),
	internal_mail_priority(HinemosPropertyBean.string("info")),
	internal_mail_subject(HinemosPropertyBean.string("")),
	internal_syslog(HinemosPropertyBean.bool(false)),
	internal_syslog_facility(HinemosPropertyBean.string("daemon")),
	internal_syslog_host(HinemosPropertyBean.string("192.168.1.1,192.168.1.2")),
	internal_syslog_port(HinemosPropertyBean.numeric(514L)),
	internal_syslog_priority(HinemosPropertyBean.string("info")),
	internal_syslog_severity(HinemosPropertyBean.string("alert")),
	internal_syslog_target_agent(HinemosPropertyBean.bool(false)),
	internal_syslog_target_agent_priority(HinemosPropertyBean.string("info")),
	internal_event_target_agent(HinemosPropertyBean.bool(true)),
	internal_event_target_agent_priority(HinemosPropertyBean.string("info")),
	job_approval_page_link(HinemosPropertyBean.string("http://192.168.1.1/#approval?LoginUrl=http://192.168.1.1:8080/HinemosWS/")),
	job_end_criteria(HinemosPropertyBean.bool(false)),
	job_end_delay_change_mount_lower_limit(HinemosPropertyBean.numeric(5L)),
	job_filecheck_replace_date_format(HinemosPropertyBean.string("yyyy/MM/dd HH:mm:ss")),
	job_hulft_mode(HinemosPropertyBean.bool(false)),
	job_hulft_script_dir_linux(HinemosPropertyBean.string(CreateHulftJob.SCRIPT_DIR_LINUX)),
	job_hulft_script_dir_windows(HinemosPropertyBean.string(CreateHulftJob.SCRIPT_DIR_WIN)),
	job_message_max_length(HinemosPropertyBean.numeric(2048L)),
	job_monitor_thread_pool_size(HinemosPropertyBean.numeric(5L)),
	job_resource_thread_pool_size(HinemosPropertyBean.numeric(5L)),
	job_rpa_thread_pool_size(HinemosPropertyBean.numeric(10L)),
	job_rpa_login_thread_pool_size(HinemosPropertyBean.numeric(10L)),
	job_rpa_login_retry_interval(HinemosPropertyBean.numeric(10000L)),
	job_rpa_login_connection_timeout(HinemosPropertyBean.numeric(15000L)), // xfreerdpのコネクションタイムアウト値
	job_rpa_request_retry_interval(HinemosPropertyBean.numeric(10000L)),
	job_rpa_request_check_interval(HinemosPropertyBean.numeric(10000L)),
	job_rpa_destroy_process(HinemosPropertyBean.bool(true)),
	job_open_forward_file_job(HinemosPropertyBean.bool(false)),
	job_param_disable(HinemosPropertyBean.string("")),
	job_param_notify_escape(HinemosPropertyBean.bool(true)),
	job_param_runjob_escape(HinemosPropertyBean.bool(false)),
	job_param_user_escape(HinemosPropertyBean.bool(false)),
	job_param_node_escape(HinemosPropertyBean.bool(true)),
	job_delete_premake_thread_pool_size(HinemosPropertyBean.numeric(1L)),
	job_delete_premake_select_timeout(HinemosPropertyBean.numeric(15000L)),
	job_retry_interval(HinemosPropertyBean.numeric(Long.valueOf(10 * 1000))),
	job_schedule_plan_max(HinemosPropertyBean.numeric(2030L)),
	job_script_maxsize(HinemosPropertyBean.numeric(8192L)),
	job_session_change_data_analysys_count(HinemosPropertyBean.numeric(30L)),
	job_session_change_data_analysys_range(HinemosPropertyBean.numeric(43200L)),
	joblink_send_job_thread_pool_size(HinemosPropertyBean.numeric(5L)),
	joblink_rcv_job_thread_pool_size(HinemosPropertyBean.numeric(5L)),
	joblinkmes_message_max_length(HinemosPropertyBean.numeric(255L)),
	joblinkmes_messageorg_max_length(HinemosPropertyBean.numeric(1024L)),
	joblinkmes_transport_retry_interval(HinemosPropertyBean.numeric(10000L)),
	jobqueue_size(HinemosPropertyBean.numeric(1000L)),
	jobqueue_executor_threadPool_size(HinemosPropertyBean.numeric(2L)),
	jobmap_icon_id_default_approvaljob(HinemosPropertyBean.string("APPROVALJOB_DEFAULT")),
	jobmap_icon_id_default_filejob(HinemosPropertyBean.string("FILEJOB_DEFAULT")),
	jobmap_icon_id_default_job(HinemosPropertyBean.string("JOB_DEFAULT")),
	jobmap_icon_id_default_jobnet(HinemosPropertyBean.string("JOBNET_DEFAULT")),
	jobmap_icon_id_default_monitorjob(HinemosPropertyBean.string("MONITORJOB_DEFAULT")),
	jobmap_icon_id_default_filecheckjob(HinemosPropertyBean.string("FILECHECKJOB_DEFAULT")),
	jobmap_icon_id_default_resourcejob(HinemosPropertyBean.string("RESOURCEJOB_DEFAULT")),
	jobmap_icon_id_default_joblinksendjob(HinemosPropertyBean.string("JOBLINKSENDJOB_DEFAULT")),
	jobmap_icon_id_default_joblinkrcvjob(HinemosPropertyBean.string("JOBLINKRCVJOB_DEFAULT")),
	jobmap_icon_id_default_rpajob(HinemosPropertyBean.string("RPA_DEFAULT")),
	mail_$_allow8bitmime(HinemosPropertyBean.bool()),
	mail_$_auth(HinemosPropertyBean.bool()),
	mail_$_auth_digest_md5_disable(HinemosPropertyBean.bool()),
	mail_$_auth_login_disable(HinemosPropertyBean.bool()),
	mail_$_auth_mechanisms(HinemosPropertyBean.string()),
	mail_$_auth_ntlm_disable(HinemosPropertyBean.bool()),
	mail_$_auth_ntlm_domain(HinemosPropertyBean.string()),
	mail_$_auth_ntlm_flags(HinemosPropertyBean.numeric()),
	mail_$_auth_plain_disable(HinemosPropertyBean.bool()),
	mail_$_connectiontimeout(HinemosPropertyBean.numeric(15000L)),
	mail_$_dsn_notify(HinemosPropertyBean.string()),
	mail_$_dsn_ret(HinemosPropertyBean.string()),
	mail_$_ehlo(HinemosPropertyBean.bool()),
	mail_$_from(HinemosPropertyBean.string()),
	mail_$_host(HinemosPropertyBean.string()),
	mail_$_localaddress(HinemosPropertyBean.string()),
	mail_$_localhost(HinemosPropertyBean.string()),
	mail_$_localport(HinemosPropertyBean.numeric()),
	mail_$_mailextension(HinemosPropertyBean.string()),
	mail_$_noop_strict(HinemosPropertyBean.bool()),
	mail_$_port(HinemosPropertyBean.numeric()),
	mail_$_quitwait(HinemosPropertyBean.bool()),
	mail_$_reportsuccess(HinemosPropertyBean.bool()),
	mail_$_sasl_authorizationid(HinemosPropertyBean.string()),
	mail_$_sasl_enable(HinemosPropertyBean.bool()),
	mail_$_sasl_mechanisms(HinemosPropertyBean.string()),
	mail_$_sasl_realm(HinemosPropertyBean.string()),
	mail_$_sasl_usecanonicalhostname(HinemosPropertyBean.bool()),
	mail_$_sendpartial(HinemosPropertyBean.bool()),
	mail_$_socketFactory_class(HinemosPropertyBean.string()),
	mail_$_socketFactory_fallback(HinemosPropertyBean.bool()),
	mail_$_socketFactory_port(HinemosPropertyBean.numeric()),
	mail_$_socks_host(HinemosPropertyBean.string()),
	mail_$_socks_port(HinemosPropertyBean.string()),
	mail_$_starttls_enable(HinemosPropertyBean.bool()),
	mail_$_starttls_required(HinemosPropertyBean.bool()),
	mail_$_submitter(HinemosPropertyBean.string()),
	mail_$_timeout(HinemosPropertyBean.numeric(30000L)),
	mail_$_user(HinemosPropertyBean.string()),
	mail_$_userset(HinemosPropertyBean.bool()),
	mail_$_writetimeout(HinemosPropertyBean.numeric()),
	mail_oauth_refresh_token_path(HinemosPropertyBean.string()),
	mail_oauth_response_key(HinemosPropertyBean.string("access_token")),
	mail_oauth_url(HinemosPropertyBean.string()),
	mail_oauth_param_key1(HinemosPropertyBean.string()),
	mail_oauth_param_key2(HinemosPropertyBean.string()),
	mail_oauth_param_key3(HinemosPropertyBean.string()),
	mail_oauth_param_key4(HinemosPropertyBean.string()),
	mail_oauth_param_key5(HinemosPropertyBean.string()),
	mail_oauth_param_key6(HinemosPropertyBean.string()),
	mail_oauth_param_key7(HinemosPropertyBean.string()),
	mail_oauth_param_key8(HinemosPropertyBean.string()),
	mail_oauth_param_key9(HinemosPropertyBean.string()),
	mail_oauth_param_key10(HinemosPropertyBean.string()),
	mail_oauth_param_value1(HinemosPropertyBean.string()),
	mail_oauth_param_value2(HinemosPropertyBean.string()),
	mail_oauth_param_value3(HinemosPropertyBean.string()),
	mail_oauth_param_value4(HinemosPropertyBean.string()),
	mail_oauth_param_value5(HinemosPropertyBean.string()),
	mail_oauth_param_value6(HinemosPropertyBean.string()),
	mail_oauth_param_value7(HinemosPropertyBean.string()),
	mail_oauth_param_value8(HinemosPropertyBean.string()),
	mail_oauth_param_value9(HinemosPropertyBean.string()),
	mail_oauth_param_value10(HinemosPropertyBean.string()),
	mail_charset_address(HinemosPropertyBean.string("UTF-8")),
	mail_charset_content(HinemosPropertyBean.string("UTF-8")),
	mail_charset_subject(HinemosPropertyBean.string("UTF-8")),
	mail_debug(HinemosPropertyBean.bool(false)),
	mail_enable_send_all_server(HinemosPropertyBean.bool(false)),
	mail_errors_to_address(HinemosPropertyBean.string("admin@hinemos.com")),
	mail_from_address(HinemosPropertyBean.string("admin@hinemos.com")),
	mail_from_personal_name(HinemosPropertyBean.string("Hinemos Admin")),
	mail_native_to_ascii(HinemosPropertyBean.bool(false)),
	mail_reply_personal_name(HinemosPropertyBean.string("Hinemos Admin")),
	mail_reply_to_address(HinemosPropertyBean.string("admin@hinemos.com")),
	mail_smtp_ssl_checkserveridentity(HinemosPropertyBean.bool()),
	mail_smtp_ssl_ciphersuites(HinemosPropertyBean.string()),
	mail_smtp_ssl_enable(HinemosPropertyBean.bool()),
	mail_smtp_ssl_protocols(HinemosPropertyBean.string()),
	mail_smtp_ssl_socketFactory_class(HinemosPropertyBean.string()),
	mail_smtp_ssl_socketFactory_port(HinemosPropertyBean.numeric()),
	mail_smtp_ssl_trust(HinemosPropertyBean.string()),
	mail_store_protocol(HinemosPropertyBean.string("pop3")),
	mail_transport_password(HinemosPropertyBean.string("password")),
	mail_transport_protocol(HinemosPropertyBean.string("smtp")),
	mail_transport_tries(HinemosPropertyBean.numeric(1L)),
	mail_transport_tries_interval(HinemosPropertyBean.numeric(10000L)),
	mail_transport_user(HinemosPropertyBean.string("nobody")),
	mail_$_charset_address(HinemosPropertyBean.string("UTF-8")),
	mail_$_charset_content(HinemosPropertyBean.string("UTF-8")),
	mail_$_charset_subject(HinemosPropertyBean.string("UTF-8")),
	mail_$_debug(HinemosPropertyBean.bool(false)),
	mail_$_errors_to_address(HinemosPropertyBean.string("admin@hinemos.com")),
	mail_$_from_address(HinemosPropertyBean.string("admin@hinemos.com")),
	mail_$_from_personal_name(HinemosPropertyBean.string("Hinemos Admin")),
	mail_$_native_to_ascii(HinemosPropertyBean.bool(false)),
	mail_$_reply_personal_name(HinemosPropertyBean.string("Hinemos Admin")),
	mail_$_reply_to_address(HinemosPropertyBean.string("admin@hinemos.com")),
	mail_$_smtp_ssl_checkserveridentity(HinemosPropertyBean.bool()),
	mail_$_smtp_ssl_ciphersuites(HinemosPropertyBean.string()),
	mail_$_smtp_ssl_enable(HinemosPropertyBean.bool()),
	mail_$_smtp_ssl_protocols(HinemosPropertyBean.string()),
	mail_$_smtp_ssl_socketFactory_class(HinemosPropertyBean.string()),
	mail_$_smtp_ssl_socketFactory_port(HinemosPropertyBean.numeric()),
	mail_$_smtp_ssl_trust(HinemosPropertyBean.string()),
	mail_$_store_protocol(HinemosPropertyBean.string("pop3")),
	mail_$_transport_password(HinemosPropertyBean.string("password")),
	mail_$_transport_protocol(HinemosPropertyBean.string("smtp")),
	mail_$_transport_tries(HinemosPropertyBean.numeric(1L)),
	mail_$_transport_tries_interval(HinemosPropertyBean.numeric(10000L)),
	mail_$_transport_user(HinemosPropertyBean.string("nobody")),
	mail_$_server_enable(HinemosPropertyBean.bool(true)),
	mail_$_server_ownerroleid_list(HinemosPropertyBean.string("")),
	mail_$_server_failure_waittime(HinemosPropertyBean.numeric(0L)),
	mail_$_oauth_refresh_token_path(HinemosPropertyBean.string()),
	mail_$_oauth_response_key(HinemosPropertyBean.string("access_token")),
	mail_$_oauth_url(HinemosPropertyBean.string()),
	mail_$_oauth_param_key1(HinemosPropertyBean.string()),
	mail_$_oauth_param_key2(HinemosPropertyBean.string()),
	mail_$_oauth_param_key3(HinemosPropertyBean.string()),
	mail_$_oauth_param_key4(HinemosPropertyBean.string()),
	mail_$_oauth_param_key5(HinemosPropertyBean.string()),
	mail_$_oauth_param_key6(HinemosPropertyBean.string()),
	mail_$_oauth_param_key7(HinemosPropertyBean.string()),
	mail_$_oauth_param_key8(HinemosPropertyBean.string()),
	mail_$_oauth_param_key9(HinemosPropertyBean.string()),
	mail_$_oauth_param_key10(HinemosPropertyBean.string()),
	mail_$_oauth_param_value1(HinemosPropertyBean.string()),
	mail_$_oauth_param_value2(HinemosPropertyBean.string()),
	mail_$_oauth_param_value3(HinemosPropertyBean.string()),
	mail_$_oauth_param_value4(HinemosPropertyBean.string()),
	mail_$_oauth_param_value5(HinemosPropertyBean.string()),
	mail_$_oauth_param_value6(HinemosPropertyBean.string()),
	mail_$_oauth_param_value7(HinemosPropertyBean.string()),
	mail_$_oauth_param_value8(HinemosPropertyBean.string()),
	mail_$_oauth_param_value9(HinemosPropertyBean.string()),
	mail_$_oauth_param_value10(HinemosPropertyBean.string()),
	mail_$_smtp_allow8bitmime(HinemosPropertyBean.bool()),
	mail_$_smtp_auth(HinemosPropertyBean.bool()),
	mail_$_smtp_auth_digest_md5_disable(HinemosPropertyBean.bool()),
	mail_$_smtp_auth_login_disable(HinemosPropertyBean.bool()),
	mail_$_smtp_auth_mechanisms(HinemosPropertyBean.string()),
	mail_$_smtp_auth_ntlm_disable(HinemosPropertyBean.bool()),
	mail_$_smtp_auth_ntlm_domain(HinemosPropertyBean.string()),
	mail_$_smtp_auth_ntlm_flags(HinemosPropertyBean.numeric()),
	mail_$_smtp_auth_plain_disable(HinemosPropertyBean.bool()),
	mail_$_smtp_connectiontimeout(HinemosPropertyBean.numeric(15000L)),
	mail_$_smtp_dsn_notify(HinemosPropertyBean.string()),
	mail_$_smtp_dsn_ret(HinemosPropertyBean.string()),
	mail_$_smtp_ehlo(HinemosPropertyBean.bool()),
	mail_$_smtp_from(HinemosPropertyBean.string()),
	mail_$_smtp_host(HinemosPropertyBean.string()),
	mail_$_smtp_localaddress(HinemosPropertyBean.string()),
	mail_$_smtp_localhost(HinemosPropertyBean.string()),
	mail_$_smtp_localport(HinemosPropertyBean.numeric()),
	mail_$_smtp_mailextension(HinemosPropertyBean.string()),
	mail_$_smtp_noop_strict(HinemosPropertyBean.bool()),
	mail_$_smtp_port(HinemosPropertyBean.numeric()),
	mail_$_smtp_quitwait(HinemosPropertyBean.bool()),
	mail_$_smtp_reportsuccess(HinemosPropertyBean.bool()),
	mail_$_smtp_sasl_authorizationid(HinemosPropertyBean.string()),
	mail_$_smtp_sasl_enable(HinemosPropertyBean.bool()),
	mail_$_smtp_sasl_mechanisms(HinemosPropertyBean.string()),
	mail_$_smtp_sasl_realm(HinemosPropertyBean.string()),
	mail_$_smtp_sasl_usecanonicalhostname(HinemosPropertyBean.bool()),
	mail_$_smtp_sendpartial(HinemosPropertyBean.bool()),
	mail_$_smtp_socketFactory_class(HinemosPropertyBean.string()),
	mail_$_smtp_socketFactory_fallback(HinemosPropertyBean.bool()),
	mail_$_smtp_socketFactory_port(HinemosPropertyBean.numeric()),
	mail_$_smtp_socks_host(HinemosPropertyBean.string()),
	mail_$_smtp_socks_port(HinemosPropertyBean.string()),
	mail_$_smtp_starttls_enable(HinemosPropertyBean.bool()),
	mail_$_smtp_starttls_required(HinemosPropertyBean.bool()),
	mail_$_smtp_submitter(HinemosPropertyBean.string()),
	mail_$_smtp_timeout(HinemosPropertyBean.numeric(30000L)),
	mail_$_smtp_user(HinemosPropertyBean.string()),
	mail_$_smtp_userset(HinemosPropertyBean.bool()),
	mail_$_smtp_writetimeout(HinemosPropertyBean.numeric()),
	mail_$_smtps_allow8bitmime(HinemosPropertyBean.bool()),
	mail_$_smtps_auth(HinemosPropertyBean.bool()),
	mail_$_smtps_auth_digest_md5_disable(HinemosPropertyBean.bool()),
	mail_$_smtps_auth_login_disable(HinemosPropertyBean.bool()),
	mail_$_smtps_auth_mechanisms(HinemosPropertyBean.string()),
	mail_$_smtps_auth_ntlm_disable(HinemosPropertyBean.bool()),
	mail_$_smtps_auth_ntlm_domain(HinemosPropertyBean.string()),
	mail_$_smtps_auth_ntlm_flags(HinemosPropertyBean.numeric()),
	mail_$_smtps_auth_plain_disable(HinemosPropertyBean.bool()),
	mail_$_smtps_connectiontimeout(HinemosPropertyBean.numeric(15000L)),
	mail_$_smtps_dsn_notify(HinemosPropertyBean.string()),
	mail_$_smtps_dsn_ret(HinemosPropertyBean.string()),
	mail_$_smtps_ehlo(HinemosPropertyBean.bool()),
	mail_$_smtps_from(HinemosPropertyBean.string()),
	mail_$_smtps_host(HinemosPropertyBean.string()),
	mail_$_smtps_localaddress(HinemosPropertyBean.string()),
	mail_$_smtps_localhost(HinemosPropertyBean.string()),
	mail_$_smtps_localport(HinemosPropertyBean.numeric()),
	mail_$_smtps_mailextension(HinemosPropertyBean.string()),
	mail_$_smtps_noop_strict(HinemosPropertyBean.bool()),
	mail_$_smtps_port(HinemosPropertyBean.numeric()),
	mail_$_smtps_quitwait(HinemosPropertyBean.bool()),
	mail_$_smtps_reportsuccess(HinemosPropertyBean.bool()),
	mail_$_smtps_sasl_authorizationid(HinemosPropertyBean.string()),
	mail_$_smtps_sasl_enable(HinemosPropertyBean.bool()),
	mail_$_smtps_sasl_mechanisms(HinemosPropertyBean.string()),
	mail_$_smtps_sasl_realm(HinemosPropertyBean.string()),
	mail_$_smtps_sasl_usecanonicalhostname(HinemosPropertyBean.bool()),
	mail_$_smtps_sendpartial(HinemosPropertyBean.bool()),
	mail_$_smtps_socketFactory_class(HinemosPropertyBean.string()),
	mail_$_smtps_socketFactory_fallback(HinemosPropertyBean.bool()),
	mail_$_smtps_socketFactory_port(HinemosPropertyBean.numeric()),
	mail_$_smtps_socks_host(HinemosPropertyBean.string()),
	mail_$_smtps_socks_port(HinemosPropertyBean.string()),
	mail_$_smtps_starttls_enable(HinemosPropertyBean.bool()),
	mail_$_smtps_starttls_required(HinemosPropertyBean.bool()),
	mail_$_smtps_submitter(HinemosPropertyBean.string()),
	mail_$_smtps_timeout(HinemosPropertyBean.numeric(30000L)),
	mail_$_smtps_user(HinemosPropertyBean.string()),
	mail_$_smtps_userset(HinemosPropertyBean.bool()),
	mail_$_smtps_writetimeout(HinemosPropertyBean.numeric()),
	maintenance_query_timeout(HinemosPropertyBean.numeric(0L)),
	maintenance_job_history_deletion_timeout(HinemosPropertyBean.numeric(3600L)),
	maintenance_job_history_deletion_schedule_date (HinemosPropertyBean.bool(false)),
	maintenance_event_history_deletion_timeout(HinemosPropertyBean.numeric(3600L)),
	maintenance_collect_data_raw_history_deletion_timeout(HinemosPropertyBean.numeric(3600L)),
	maintenance_collect_summary_hour_history_deletion_timeout(HinemosPropertyBean.numeric(3600L)),
	maintenance_collect_summary_day_history_deletion_timeout(HinemosPropertyBean.numeric(3600L)),
	maintenance_collect_summary_month_history_deletion_timeout(HinemosPropertyBean.numeric(3600L)),
	maintenance_collect_data_string_history_deletion_timeout(HinemosPropertyBean.numeric(3600L)),
	maintenance_collect_data_binary_history_deletion_timeout(HinemosPropertyBean.numeric(3600L)),
	maintenance_node_history_deletion_timeout(HinemosPropertyBean.numeric(3600L)),
	maintenance_job_link_message_history_deletion_timeout(HinemosPropertyBean.numeric(3600L)),
	maintenance_rpa_scenario_ope_result_history_deletion_timeout(HinemosPropertyBean.numeric(3600L)),
	monitor_agent_valid_multi(HinemosPropertyBean.numeric(2L)),
	monitor_agent_valid_plus(HinemosPropertyBean.numeric(Long.valueOf(10 * 1000))),
	monitor_change_lower_limit(HinemosPropertyBean.numeric(5L)),
	monitor_common_report_event_bom(HinemosPropertyBean.bool(true)),
	monitor_common_report_event_count(HinemosPropertyBean.numeric(2000L)),
	monitor_common_report_event_format(HinemosPropertyBean.string("yyyy/MM/dd HH:mm:ss")),
	monitor_common_report_event_separator(HinemosPropertyBean.string(",")),
	monitor_common_thread_pool(HinemosPropertyBean.numeric(10L)),
	monitor_correlation_lower_limit(HinemosPropertyBean.numeric(5L)),
	monitor_custom_valid_second(HinemosPropertyBean.numeric(15L)),
	monitor_customtrap_charset(HinemosPropertyBean.string("UTF-8")),
	monitor_customtrap_http_backlog_size(HinemosPropertyBean.numeric(0L)),
	monitor_customtrap_http_pool_size(HinemosPropertyBean.numeric(1L)),
	monitor_customtrap_http_queue_size(HinemosPropertyBean.numeric(Long.valueOf(15 * 60 * 30))),
	monitor_Customtrap_RecentData_Map_size(HinemosPropertyBean.numeric(256L)),
	monitor_customtrap_stats_interval(HinemosPropertyBean.numeric(100L)),
	monitor_customtrap_url(HinemosPropertyBean.string("http://0.0.0.0:8082/")),
	monitor_event_customcmd_cmd$_enable(HinemosPropertyBean.bool(false)),
	monitor_event_customcmd_cmd$_displayname(HinemosPropertyBean.string("")),
	monitor_event_customcmd_cmd$_description(HinemosPropertyBean.string("")),
	monitor_event_customcmd_cmd$_command(HinemosPropertyBean.string("")),
	monitor_event_customcmd_cmd$_warnrc(HinemosPropertyBean.numeric(1L)),
	monitor_event_customcmd_cmd$_errorrc(HinemosPropertyBean.numeric(2L)),
	monitor_event_customcmd_cmd$_max_eventsize(HinemosPropertyBean.numeric(10L)),
	monitor_event_customcmd_cmd$_thread(HinemosPropertyBean.numeric(5L)),
	monitor_event_customcmd_cmd$_queue(HinemosPropertyBean.numeric(20L)),
	monitor_event_customcmd_cmd$_run_interval(HinemosPropertyBean.numeric(0L)),
	monitor_event_customcmd_cmd$_date_format(HinemosPropertyBean.string("yyyyMMddHHmmssSSS")),
	monitor_event_customcmd_cmd$_user(HinemosPropertyBean.string("")),
	monitor_event_customcmd_cmd$_timeout(HinemosPropertyBean.numeric(60000L)),
	monitor_event_customcmd_cmd$_buffer(HinemosPropertyBean.numeric(512L)),
	monitor_event_customcmd_cmd$_mode(HinemosPropertyBean.string("auto")),
	monitor_event_customcmd_cmd$_login(HinemosPropertyBean.bool(false)),
	monitor_event_customcmd_cmd$_result_keeptime(HinemosPropertyBean.numeric(600000L)),
	monitor_event_customcmd_cmd$_result_polling_delay(HinemosPropertyBean.numeric(5000L)),
	monitor_event_customcmd_cmd$_result_polling_interval(HinemosPropertyBean.numeric(30000L)),
	monitor_event_useritem_item$_cache_size(HinemosPropertyBean.numeric(128L)),
	monitor_event_useritem_item$_display_enable(HinemosPropertyBean.bool(false)),
	monitor_event_useritem_item$_export_enable(HinemosPropertyBean.bool(false)),
	monitor_event_useritem_item$_displayname(HinemosPropertyBean.string("")),
	monitor_event_useritem_item$_regist_initvalue(HinemosPropertyBean.string("")),
	monitor_event_useritem_item$_modify_client_enable(HinemosPropertyBean.bool(false)),
	monitor_event_useritem_item$_modify_required(HinemosPropertyBean.bool(false)),
	monitor_event_useritem_item$_modify_validation(HinemosPropertyBean.string("")),
	monitor_event_useritem_item$_modify_format(HinemosPropertyBean.string("")),
	monitor_event_eventno_display_enable(HinemosPropertyBean.bool(false)),
	monitor_event_eventno_export_enable(HinemosPropertyBean.bool(false)),
	monitor_history_facility_id_max_count(HinemosPropertyBean.numeric(1000L)),  // 非公開:テスト用
	monitor_http_content_type(HinemosPropertyBean.string("text")),
	monitor_http_post_charset(HinemosPropertyBean.string("UTF-8")),
	monitor_http_scenario_disable_proxy_cache(HinemosPropertyBean.bool(true)),
	monitor_http_ssl_trustall(HinemosPropertyBean.bool(true)),
	monitor_integration_search_timeout(HinemosPropertyBean.numeric(15000L)),
	monitor_jmx_rmi(HinemosPropertyBean.numeric(0L)),
	monitor_jmx_rmi_format_$(HinemosPropertyBean.string()),
	monitor_jmx_rmi_name_$(HinemosPropertyBean.string()),
	monitor_jmx_valid_second_$(HinemosPropertyBean.numeric(15L)),
	monitor_jmx_connect_timeout_millisecond(HinemosPropertyBean.numeric(10L * 1000L)),
	monitor_jmx_read_timeout_millisecond(HinemosPropertyBean.numeric(10L * 1000L)),
	monitor_jmx_max_left_threads_count(HinemosPropertyBean.numeric(100L)),
	monitor_log_line_max_length(HinemosPropertyBean.numeric(256L)),
	monitor_logcount_search_timeout(HinemosPropertyBean.numeric(15000L)),
	monitor_node_delay_fix(HinemosPropertyBean.bool(false)),
	monitor_ping_fping_bytes(HinemosPropertyBean.numeric(56L)),
	monitor_ping_fping_count(HinemosPropertyBean.numeric(1L)),
	monitor_ping_fping_enable(HinemosPropertyBean.bool(true)),
	monitor_ping_fping_interval(HinemosPropertyBean.numeric(1000L)),
	monitor_ping_fping_timeout(HinemosPropertyBean.numeric(1000L)),
	monitor_poller_snmp_bulk_maxrepetitions(HinemosPropertyBean.numeric(10L)),
	monitor_poller_snmp_bulk_nonrepeaters(HinemosPropertyBean.numeric(0L)),
	monitor_poller_snmp_max_retry(HinemosPropertyBean.numeric(3L)),
	monitor_poller_snmp_not_v3_snmp_pool_size(HinemosPropertyBean.numeric(32L)),
	monitor_port_protocol_dns(HinemosPropertyBean.string("localhost")),
	monitor_port_protocol_dns_class(HinemosPropertyBean.string("ANY")),
	monitor_port_protocol_dns_type(HinemosPropertyBean.string("ANY")),
	monitor_port_time_second(HinemosPropertyBean.numeric(30L)),
	monitor_prediction_lower_limit(HinemosPropertyBean.numeric(5L)),
	monitor_process_collect_initdelay_second(HinemosPropertyBean.numeric(60L)),
	monitor_process_details_display(HinemosPropertyBean.bool(false)),
	monitor_process_start_second(HinemosPropertyBean.numeric(30L)),
	monitor_process_valid_second(HinemosPropertyBean.numeric(50L)),
	monitor_resource_delete_label(HinemosPropertyBean.bool(true)),
	monitor_resource_label_replace(HinemosPropertyBean.string(" Label:.*  Serial Number .*")),
	monitor_snmp_valid_second(HinemosPropertyBean.numeric(15L)),
	monitor_snmp_invalid_over_value_32(HinemosPropertyBean.bool(false)),
	monitor_snmp_invalid_over_value_64(HinemosPropertyBean.bool(false)),
	monitor_snmptrap_charset(HinemosPropertyBean.string("UTF-8")),
	monitor_snmptrap_filter_queue_size(HinemosPropertyBean.numeric(Long.valueOf(15 * 60 * 30))),
	monitor_snmptrap_filter_thread_size(HinemosPropertyBean.numeric(1L)),
	monitor_snmptrap_listen_address(HinemosPropertyBean.string("0.0.0.0")),
	monitor_snmptrap_listen_port(HinemosPropertyBean.numeric(162L)),
	monitor_snmptrap_org_message_community(HinemosPropertyBean.bool(true)),
	monitor_snmptrap_org_message_varbind(HinemosPropertyBean.bool(true)),
	monitor_snmptrap_stats_interval(HinemosPropertyBean.numeric(100L)),
	monitor_snmptrap_v3_auth_password(HinemosPropertyBean.string("authPassword")),
	monitor_snmptrap_v3_auth_protocol(HinemosPropertyBean.string("MD5")),
	monitor_snmptrap_v3_priv_password(HinemosPropertyBean.string("privPassword")),
	monitor_snmptrap_v3_priv_protocol(HinemosPropertyBean.string("DES")),
	monitor_snmptrap_v3_security_level(HinemosPropertyBean.string("noauth_nopriv")),
	monitor_snmptrap_v3_user(HinemosPropertyBean.string("hinemos")),
	monitor_sql_jdbc_driver(HinemosPropertyBean.numeric(3L)),
	monitor_sql_jdbc_driver_classname_$(HinemosPropertyBean.string()),
	monitor_sql_jdbc_driver_logintimeout_$(HinemosPropertyBean.numeric()),
	monitor_sql_jdbc_driver_name_$(HinemosPropertyBean.string()),
	monitor_sql_jdbc_driver_properties_$(HinemosPropertyBean.string()),
	monitor_status_cache_exclude_pluginid(HinemosPropertyBean.string(HinemosModuleConstant.JOB +  "," + HinemosModuleConstant.INFRA)),
	monitor_status_non_store_mode_job(HinemosPropertyBean.bool(false)),
	monitor_systemlog_filter_queue_size(HinemosPropertyBean.numeric(Long.valueOf(15 * 60 * 30))),
	monitor_systemlog_filter_thread_size(HinemosPropertyBean.numeric(1L)),
	monitor_systemlog_listen_address(HinemosPropertyBean.string("0.0.0.0")),
	monitor_systemlog_listen_port(HinemosPropertyBean.numeric(514L)),
	monitor_systemlog_listen_tcp(HinemosPropertyBean.bool(true)),
	monitor_systemlog_listen_udp(HinemosPropertyBean.bool(true)),
	monitor_systemlog_period_hour(HinemosPropertyBean.numeric(Long.valueOf(SyslogMessage.SYSLOG_DEFAULT_PERIOD_HOUR))),
	monitor_systemlog_receiverid(HinemosPropertyBean.string(System.getProperty("hinemos.manager.nodename"))),
	monitor_systemlog_shutdown_timeout(HinemosPropertyBean.numeric(60000L)),
	monitor_systemlog_stats_interval(HinemosPropertyBean.numeric(1000L)),
	monitor_systemlog_split_code(HinemosPropertyBean.string("10")),
	monitor_systemlog_message_charset(HinemosPropertyBean.string("UTF-8")),
	monitor_systemlog_header_charset(HinemosPropertyBean.string("ascii")),
	monitor_systemlog_receive_tcp_read_max_size(HinemosPropertyBean.string("4096")),
	monitor_systemlog_receive_tcp_read_timeout(HinemosPropertyBean.numeric(1000*10L)),
	monitor_systemlog_receive_udp_buffer(HinemosPropertyBean.numeric()),
	monitor_systemlog_worker_thread_max_size(HinemosPropertyBean.numeric(1000L)),
	monitor_sytemslog_worker_thread_keepalive_timeout(HinemosPropertyBean.numeric(5000L)),
	monitor_systemlog_receive_tcp_read_timeout_enable(HinemosPropertyBean.bool(true)),
	monitor_systemlog_receive_tcp_max_connection(HinemosPropertyBean.numeric(200L)),
	monitor_systemlog_receive_tcp_keepAlive(HinemosPropertyBean.bool(false)),
	monitor_systemlog_receive_tcp_backlog(HinemosPropertyBean.numeric(-1L)),
	monitor_winservice_ssl_trustall(HinemosPropertyBean.bool(true)),
	monitor_winservice_authschema(HinemosPropertyBean.string("BASIC")),
	multitenant_enable(HinemosPropertyBean.bool(false)),
	multitenant_scan_max(HinemosPropertyBean.numeric(99L)),
	multitenant_$_enable(HinemosPropertyBean.bool(false)),
	multitenant_$_roles(HinemosPropertyBean.string("")),
	multitenant_$_addressgroup(HinemosPropertyBean.string("")),
	multitenant_$_nodesearch_facilityid_prefix(HinemosPropertyBean.string("")),
	multitenant_$_xcloud_snmp_user(HinemosPropertyBean.string("")),
	multitenant_$_xcloud_snmp_port(HinemosPropertyBean.numeric(0L)),
	multitenant_$_xcloud_snmp_community(HinemosPropertyBean.string("")),
	multitenant_$_xcloud_snmp_version(HinemosPropertyBean.string("")),
	multitenant_$_xcloud_snmp_securitylevel(HinemosPropertyBean.string("")),
	multitenant_$_xcloud_snmp_auth_password(HinemosPropertyBean.string("")),
	multitenant_$_xcloud_snmp_priv_password(HinemosPropertyBean.string("")),
	multitenant_$_xcloud_snmp_auth_protocol(HinemosPropertyBean.string("")),
	multitenant_$_xcloud_snmp_priv_protocol(HinemosPropertyBean.string("")),
	multitenant_$_xcloud_snmp_timeout(HinemosPropertyBean.numeric(0L)),
	multitenant_$_xcloud_snmp_retries(HinemosPropertyBean.numeric(0L)),
	node_process_path_maxsize(HinemosPropertyBean.numeric(2097152L)),
	node_product_path_maxsize(HinemosPropertyBean.numeric(2097152L)),
	node_config_report_bom(HinemosPropertyBean.bool(true)),
	node_config_report_format(HinemosPropertyBean.string("yyyy/MM/dd HH:mm:ss")),
	node_config_report_separator(HinemosPropertyBean.string(",")),
	node_config_report_expansion(HinemosPropertyBean.bool(true)),
	node_config_search_timeout(HinemosPropertyBean.numeric(15000L)),
	nodemap_ping_runcount(HinemosPropertyBean.numeric(Long.valueOf(PingRunCountConstant.TYPE_COUNT_01))),
	nodemap_ping_runinterval(HinemosPropertyBean.numeric(Long.valueOf(PingRunIntervalConstant.TYPE_SEC_02))),
	nodemap_ping_timeout(HinemosPropertyBean.numeric(Long.valueOf(PingRunIntervalConstant.TYPE_SEC_05))),
	nodemap_search_connection_thread(HinemosPropertyBean.numeric(4L)),
	nodemap_download_node_config_count(HinemosPropertyBean.numeric(100L)),
	notify_cloud_drop_excessive_msg(HinemosPropertyBean.bool(true)),
	notify_cloud_drop_excessive_count(HinemosPropertyBean.numeric(5000L)),
	notify_cloud_send_interval(HinemosPropertyBean.numeric(500L)),
	notify_cloud_message_max_length(HinemosPropertyBean.numeric(255L)),
	notify_cloud_messageorg_max_length(HinemosPropertyBean.numeric(1024L)),
	notify_command_create_mode(HinemosPropertyBean.string("auto")),
	notify_command_thread_pool_count(HinemosPropertyBean.numeric(8L)),
	notify_command_success_exit(HinemosPropertyBean.numeric(0L)),
	notify_date_format(HinemosPropertyBean.string("yyyy/MM/dd HH:mm:ss")),
	notify_event_cache_size(HinemosPropertyBean.numeric(10000L)),
	notify_event_diff(HinemosPropertyBean.bool(false)),
	notify_event_message_max_length(HinemosPropertyBean.numeric(255L)),
	notify_event_messageorg_max_length(HinemosPropertyBean.numeric(1024L)),
	notify_initial_count_max(HinemosPropertyBean.numeric(10L)),
	notify_locale(HinemosPropertyBean.string()),
	notify_log_escalate_manager_hostname(HinemosPropertyBean.string()),
	notify_log_escalate_manager_protocol(HinemosPropertyBean.string("udp")),
	notify_log_escalate_manager_retry_count(HinemosPropertyBean.numeric(1L)),
	notify_log_escalate_manager_retry_interval(HinemosPropertyBean.numeric(10000L)),
	notify_log_escalate_manager_tcp_timeout(HinemosPropertyBean.numeric(3000L)),
	notify_mail_messageorg_max_length(HinemosPropertyBean.numeric(1024L)),
	notify_message_buffer_shutdown_timeout(HinemosPropertyBean.numeric(5000L)),
	notify_message_buffer_threshold_size(HinemosPropertyBean.numeric(10L)),
	notify_message_buffer_threshold_time(HinemosPropertyBean.numeric(200L)),
	notify_message_destination_id(HinemosPropertyBean.string("filter_manager1")),
	notify_message_source_id(HinemosPropertyBean.string("manager1")),
	notify_message_webapi_auth_token(HinemosPropertyBean.string("")),
	notify_message_webapi_connection_timeout(HinemosPropertyBean.numeric(1000L)),
	notify_message_webapi_proxy_host(HinemosPropertyBean.string("")),
	notify_message_webapi_proxy_password(HinemosPropertyBean.string("")),
	notify_message_webapi_proxy_port(HinemosPropertyBean.numeric(0L)),
	notify_message_webapi_proxy_user(HinemosPropertyBean.string("")),
	notify_message_webapi_read_timeout(HinemosPropertyBean.numeric(1000L)),
	notify_message_webapi_retry_count(HinemosPropertyBean.numeric(1L)),
	notify_message_webapi_retry_interval(HinemosPropertyBean.numeric(10000L)),
	notify_message_webapi_threads(HinemosPropertyBean.numeric(5L)),
	notify_message_webapi_url(HinemosPropertyBean.string("http://localhost:9081")),
	notify_mode(HinemosPropertyBean.string("normal")),
	notify_remove_subkey_$(HinemosPropertyBean.bool()),
	notify_replace_after(HinemosPropertyBean.string("?")),
	notify_replace_before(HinemosPropertyBean.string("0")),
	notify_rest_ssl_trustall(HinemosPropertyBean.bool(true)),
	performance_export_encode(HinemosPropertyBean.string("MS932")),
	performance_export_fetchsize(HinemosPropertyBean.numeric(1000L)),
	performance_export_line_separator(HinemosPropertyBean.string("CRLF")),
	performance_list_filter_displayname(HinemosPropertyBean.string(".*")),
	performance_list_size(HinemosPropertyBean.numeric(8000L)),
	replace_param_max(HinemosPropertyBean.numeric(1000L)),
	reporting_failure_retention_period(HinemosPropertyBean.numeric(86400000L)),
	repository_agentupdate_expires(HinemosPropertyBean.numeric(60000L)),
	repository_agentupdate_interval(HinemosPropertyBean.numeric(500L)),
	repository_agentupdate_limit(HinemosPropertyBean.numeric(4L)),
	repository_agentupdate_cache_cooldown(HinemosPropertyBean.numeric(5000L)),
	repository_auto_device_find_log(HinemosPropertyBean.bool(false)),
	repository_auto_device_user(HinemosPropertyBean.string(UserIdConstant.HINEMOS)),
	repository_device_encoding(HinemosPropertyBean.string("UTF-8,MS932")),
	repository_device_search_interval(HinemosPropertyBean.numeric(5L)),
	repository_device_search_prop_basic_agent(HinemosPropertyBean.bool(false)),
	repository_device_search_prop_basic_hardware(HinemosPropertyBean.bool(false)),
	repository_device_search_prop_basic_network(HinemosPropertyBean.bool(true)),
	repository_device_search_prop_basic_os(HinemosPropertyBean.bool(false)),
	repository_device_search_prop_device_cpu(HinemosPropertyBean.bool(true)),
	repository_device_search_prop_device_disk(HinemosPropertyBean.bool(true)),
	repository_device_search_prop_device_filesystem(HinemosPropertyBean.bool(true)),
	repository_device_search_prop_device_general(HinemosPropertyBean.bool(false)),
	repository_device_search_prop_device_memory(HinemosPropertyBean.bool(true)),
	repository_device_search_prop_device_nic(HinemosPropertyBean.bool(true)),
	repository_device_search_prop_node_config_hostname(HinemosPropertyBean.bool(true)),
	repository_device_search_threadpool_size(HinemosPropertyBean.numeric(5L)),
	repository_device_search_verbose(HinemosPropertyBean.bool(false)),
	repository_node_config_collect_load_distribution_range(HinemosPropertyBean.numeric(-1L)), // (単位:分).
	repository_node_config_collect_reference_time(HinemosPropertyBean.string("00:00")), // HH:mm 24時間表記.
	repository_node_config_nodename_update_priority(HinemosPropertyBean.string("device_search")),
	repository_node_config_run_clean_interval(HinemosPropertyBean.numeric(360L)), // 6時間(単位:分).
	repository_node_config_run_distribution_time(HinemosPropertyBean.numeric(600000L)), // 10分(単位:ミリ秒).
	repository_node_config_run_sleep(HinemosPropertyBean.numeric(500L)), // 0.5秒(単位:ミリ秒).
	repository_node_config_run_too_old(HinemosPropertyBean.numeric(600000L)), // 10分(単位:ミリ秒).
	repository_node_replace_max_by_key(HinemosPropertyBean.numeric(1000L)),
	repository_node_replace_separator(HinemosPropertyBean.string(",")),
	repository_node_replace_line_separator(HinemosPropertyBean.string("CRLF")),
	repository_node_replace_date_format(HinemosPropertyBean.string("yyyy/MM/dd HH:mm:ss")),
	repository_node_search_delay(HinemosPropertyBean.numeric(10L)),
	repository_node_search_max_node(HinemosPropertyBean.numeric(256L)),
	repository_node_search_timeout(HinemosPropertyBean.numeric(Long.valueOf(50 * 1000))),
	repository_nodename_fqdn(HinemosPropertyBean.bool(false)),
	repository_restart_sleep(HinemosPropertyBean.numeric(500L)),
	repository_snmp_oid_contact(HinemosPropertyBean.string(".1.3.6.1.2.1.1.4.0")),
	repository_snmp_oid_cpu_index(HinemosPropertyBean.string(".1.3.6.1.2.1.25.3.3.1.2")),
	repository_snmp_oid_descr(HinemosPropertyBean.string(".1.3.6.1.2.1.1.1.0")),
	repository_snmp_oid_disk_index(HinemosPropertyBean.string(".1.3.6.1.4.1.2021.13.15.1.1.1")),
	repository_snmp_oid_disk_io_read(HinemosPropertyBean.string(".1.3.6.1.4.1.2021.13.15.1.1.5")),
	repository_snmp_oid_disk_io_write(HinemosPropertyBean.string(".1.3.6.1.4.1.2021.13.15.1.1.6")),
	repository_snmp_oid_disk_ion_read(HinemosPropertyBean.string(".1.3.6.1.4.1.2021.13.15.1.1.3")),
	repository_snmp_oid_disk_ion_write(HinemosPropertyBean.string(".1.3.6.1.4.1.2021.13.15.1.1.4")),
	repository_snmp_oid_disk_name(HinemosPropertyBean.string(".1.3.6.1.4.1.2021.13.15.1.1.2")),
	repository_snmp_oid_filesystem_index(HinemosPropertyBean.string(".1.3.6.1.2.1.25.2.3.1.1")),
	repository_snmp_oid_filesystem_name(HinemosPropertyBean.string(".1.3.6.1.2.1.25.2.3.1.3")),
	repository_snmp_oid_filesystem_size(HinemosPropertyBean.string(".1.3.6.1.2.1.25.2.3.1.5")),
	repository_snmp_oid_filesystem_type(HinemosPropertyBean.string(".1.3.6.1.2.1.25.2.3.1.2")),
	repository_snmp_oid_name(HinemosPropertyBean.string(".1.3.6.1.2.1.1.5.0")),
	repository_snmp_oid_nic_in_octet(HinemosPropertyBean.string(".1.3.6.1.2.1.2.2.1.10")),
	repository_snmp_oid_nic_index(HinemosPropertyBean.string(".1.3.6.1.2.1.2.2.1.1")),
	repository_snmp_oid_nic_ipv4_address(HinemosPropertyBean.string(".1.3.6.1.2.1.4.34.1.3.1.4")),
	repository_snmp_oid_nic_ipv4_address_type(HinemosPropertyBean.string(".1.3.6.1.2.1.4.34.1.4.1.4")),
	repository_snmp_oid_nic_ipv6_address(HinemosPropertyBean.string(".1.3.6.1.2.1.4.34.1.3.2.16")),
	repository_snmp_oid_nic_ipv6_address_type(HinemosPropertyBean.string(".1.3.6.1.2.1.4.34.1.4.2.16")),
	repository_snmp_oid_nic_mac_address(HinemosPropertyBean.string(".1.3.6.1.2.1.2.2.1.6")),
	repository_snmp_oid_nic_name(HinemosPropertyBean.string(".1.3.6.1.2.1.2.2.1.2")),
	repository_snmp_oid_nic_out_octet(HinemosPropertyBean.string(".1.3.6.1.2.1.2.2.1.16")),
	repository_snmp_retry(HinemosPropertyBean.numeric(1L)),
	repository_snmp_timeout(HinemosPropertyBean.numeric(5000L)),
	rest_agent_address(HinemosPropertyBean.string("http://0.0.0.0:8083/")),
	rest_agent_queue_size(HinemosPropertyBean.numeric(1200L)),
	rest_agent_request_id_keep_minutes(HinemosPropertyBean.numeric(30L)),
	rest_agent_threadpool_size(HinemosPropertyBean.numeric(8L)),
	rest_agent_shutdown_timeout(HinemosPropertyBean.numeric(10000L)),
	rest_client_address(HinemosPropertyBean.string("http://0.0.0.0:8080/")),
	rest_client_threadpool_size(HinemosPropertyBean.numeric(8L)),
	rest_client_shutdown_timeout(HinemosPropertyBean.numeric(10000L)),
	rest_cors_access_control_allow_origin(HinemosPropertyBean.string("*")),
	rest_https_protocol(HinemosPropertyBean.string("TLS")),
	rest_httpserver_maxheadersize(HinemosPropertyBean.numeric(1048576L)),
	rest_operation_log_length(HinemosPropertyBean.numeric(1048576L)),
	rest_queue_size(HinemosPropertyBean.numeric(300L)),
	rest_token_valid_term_minutes(HinemosPropertyBean.numeric(1440L)),
	rest_datetime_format(HinemosPropertyBean.string("yyyy-MM-dd HH:mm:ss.SSS")),
	rest_cluster_threadpool_size(HinemosPropertyBean.numeric(8L)),
	rest_cluster_shutdown_timeout(HinemosPropertyBean.numeric(60000L)),
	rest_clusterMonitor_threadpool_size(HinemosPropertyBean.numeric(2L)),
	rest_clusterMonitor_shutdown_timeout(HinemosPropertyBean.numeric(60000L)),
	rpa_collect_analyze_fetch_size(HinemosPropertyBean.numeric(10000L)),
	rpa_collect_analyze_maxsize(HinemosPropertyBean.numeric(50000L)),
	rpa_collect_scenario_classify_node(HinemosPropertyBean.bool(false)),
	rpa_update_scenario_operation_result_interval(HinemosPropertyBean.string("0 */10 * * * ?")),
	rpa_update_scenario_operation_result_maxsize(HinemosPropertyBean.numeric(50000L)),
	rpa_internal_thread_admin_user(HinemosPropertyBean.string("hinemos")),
	rpa_autoupdate_enable(HinemosPropertyBean.bool(true)),
	rpa_autoupdate_interval(HinemosPropertyBean.string("0 */10 * * * ?")),
	rpa_autoupdate_notify_add_node(HinemosPropertyBean.bool(true)),
	rpa_autoupdate_notify_change_node(HinemosPropertyBean.bool(true)),
	rpa_autoupdate_notify_delete_node(HinemosPropertyBean.bool(true)),
	rpa_scenario_operation_result_download_csv_bom(HinemosPropertyBean.bool(true)),
	rpa_scenario_operation_result_download_csv_charset(HinemosPropertyBean.string("UTF-8")),
	rpa_scenario_operation_result_download_csv_line_separator(HinemosPropertyBean.string("CRLF")),
	rpa_management_rest_client_config_connection_timeout(HinemosPropertyBean.numeric(10l * 1000)),
	rpa_management_rest_client_config_read_timeout(HinemosPropertyBean.numeric(10l * 1000)),
	rpa_management_rest_client_config_ssl_trustall(HinemosPropertyBean.bool(true)),
	rpa_management_rest_windirector_token_expired_millis(HinemosPropertyBean.numeric(0L)),  // WinDirectorのトークンは有効期限なし
	rpa_management_rest_winactor_manager_on_cloud_token_expired_millis(HinemosPropertyBean.numeric(60L * 1000)),
	rpa_management_rest_uipath_orchestrator_on_premise_token_expired_millis(HinemosPropertyBean.numeric(60L * 1000)),
	rpa_management_rest_uipath_orchestrator_cloud_token_expired_millis(HinemosPropertyBean.numeric(60L * 1000)),
	rpa_ipaddress_notavailable(HinemosPropertyBean.string("169.254.0.0")),
	rpa_node_property_node_variablename(HinemosPropertyBean.string("")),
	rpa_node_property_node_variablevalue(HinemosPropertyBean.string("")),
	rpa_node_property_agent_awakeport(HinemosPropertyBean.numeric(24005L)),
	rpa_node_property_job_priority(HinemosPropertyBean.numeric(16L)),
	rpa_node_property_job_multiplicity(HinemosPropertyBean.numeric(0L)),
	rpa_node_property_snmp_user(HinemosPropertyBean.string("root")),
	rpa_node_property_snmp_port(HinemosPropertyBean.numeric(161L)),
	rpa_node_property_snmp_community(HinemosPropertyBean.string("public")),
	rpa_node_property_snmp_version(HinemosPropertyBean.string(SnmpVersionConstant.STRING_V2)),
	rpa_node_property_snmp_securitylevel(HinemosPropertyBean.string("noauth_nopriv")),
	rpa_node_property_snmp_auth_password(HinemosPropertyBean.string("")),
	rpa_node_property_snmp_priv_password(HinemosPropertyBean.string("")),
	rpa_node_property_snmp_auth_protocol(HinemosPropertyBean.string("MD5")),
	rpa_node_property_snmp_priv_protocol(HinemosPropertyBean.string("DES")),
	rpa_node_property_snmp_timeout(HinemosPropertyBean.numeric(5000L)),
	rpa_node_property_snmp_retries(HinemosPropertyBean.numeric(3L)),
	rpa_node_property_wbem_user(HinemosPropertyBean.string("root")),
	rpa_node_property_wbem_userpassword(HinemosPropertyBean.string("")),
	rpa_node_property_wbem_port(HinemosPropertyBean.numeric(5988L)),
	rpa_node_property_wbem_protocol(HinemosPropertyBean.string("http")),
	rpa_node_property_wbem_timeout(HinemosPropertyBean.numeric(5000L)),
	rpa_node_property_wbem_retries(HinemosPropertyBean.numeric(3L)),
	rpa_node_property_ipmi_ipaddress(HinemosPropertyBean.string("")),
	rpa_node_property_ipmi_port(HinemosPropertyBean.numeric(0L)),
	rpa_node_property_ipmi_user(HinemosPropertyBean.string("")),
	rpa_node_property_ipmi_userpassword(HinemosPropertyBean.string("")),
	rpa_node_property_ipmi_timeout(HinemosPropertyBean.numeric(5000L)),
	rpa_node_property_ipmi_retries(HinemosPropertyBean.numeric(3L)),
	rpa_node_property_ipmi_protocol(HinemosPropertyBean.string("RMCP+")),
	rpa_node_property_ipmi_level(HinemosPropertyBean.string("")),
	rpa_node_property_winrm_user(HinemosPropertyBean.string("")),
	rpa_node_property_winrm_userpassword(HinemosPropertyBean.string("")),
	rpa_node_property_winrm_version(HinemosPropertyBean.string("2.0")),
	rpa_node_property_winrm_port(HinemosPropertyBean.numeric(5985L)),
	rpa_node_property_winrm_protocol(HinemosPropertyBean.string("http")),
	rpa_node_property_winrm_timeout(HinemosPropertyBean.numeric(5000L)),
	rpa_node_property_winrm_retries(HinemosPropertyBean.numeric(3L)),
	rpa_node_property_ssh_user(HinemosPropertyBean.string("root")),
	rpa_node_property_ssh_userpassword(HinemosPropertyBean.string("")),
	rpa_node_property_ssh_privkey_path(HinemosPropertyBean.string("")),
	rpa_node_property_ssh_privkey_passphrase(HinemosPropertyBean.string("")),
	rpa_node_property_ssh_port(HinemosPropertyBean.numeric(22L)),
	rpa_node_property_ssh_timeout(HinemosPropertyBean.numeric(50000L)),
	rpa_node_property_administrator(HinemosPropertyBean.string("")),
	rpa_node_property_contact(HinemosPropertyBean.string("")),
	scheduler_dbms_misfireThreshold(HinemosPropertyBean.numeric(3600000L)),
	scheduler_dbms_job_threadPool_size(HinemosPropertyBean.numeric(8L)),
	scheduler_dbms_del_threadPool_size(HinemosPropertyBean.numeric(4L)),
	scheduler_dbms_trans_threadPool_size(HinemosPropertyBean.numeric(4L)),
	scheduler_dbms_postpone_delay(HinemosPropertyBean.numeric(200L)),
	scheduler_dbms_postpone_limit(HinemosPropertyBean.numeric(100L)),
	scheduler_job_cron(HinemosPropertyBean.string("0 */1 * * * ? *")),
	scheduler_monitor_cron(HinemosPropertyBean.string("0 */5 * * * ? *")),
	scheduler_monitor_status_cron(HinemosPropertyBean.string("50 3/10 * * * ? *")),
	scheduler_ram_monitor_misfireThreshold(HinemosPropertyBean.numeric(3600000L)),
	scheduler_ram_monitor_threadPool_size(HinemosPropertyBean.numeric(25L)),
	scheduler_ram_job_misfireThreshold(HinemosPropertyBean.numeric(3600000L)),
	scheduler_ram_job_threadPool_size(HinemosPropertyBean.numeric(10L)),
	scheduler_repository_cron(HinemosPropertyBean.string("40 */1 * * * ? *")),
	selfcheck_alert_threshold(HinemosPropertyBean.numeric(3L)),
	selfcheck_interval(HinemosPropertyBean.numeric(150L)),
	selfcheck_monitoring_asynctask_queue(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_asynctask_queue_list(HinemosPropertyBean.string(
			"NotifyStatusTaskFactory:10000,NotifyEventTaskFactory:10000,NotifyMailTaskFactory:10000," +
			"NotifyCommandTaskFactory:10000,NotifyLogEscalationTaskFactory:10000,NotifyJobTaskFactory:10000," +
			"CreateJobSessionTaskFactory:100,NotifyInfraTaskFactory:10000,NotifyRestTaskFactory:10000," +
			"NotifyCloudTaskFactory:10000,AgentRestartTaskFactory:10000," +
			"AgentUpdateTaskFactory:10000,NotifyMessageTaskFactory:10000")),
	selfcheck_monitoring_db(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_db_connection_count(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_db_connection_count_threshold(HinemosPropertyBean.numeric(80L)),
	selfcheck_monitoring_dbsize(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_dbsize_threshold(HinemosPropertyBean.numeric(10240L)),
	selfcheck_monitoring_dbtran(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_dbtran_interval(HinemosPropertyBean.numeric(86400L)),
	selfcheck_monitoring_filesystem_usage(HinemosPropertyBean.bool(false)),
	selfcheck_monitoring_filesystem_usage_list(HinemosPropertyBean.string("/:50")),
	selfcheck_monitoring_job_runningsession(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_job_runningsession_threshold(HinemosPropertyBean.numeric(1000L)),
	selfcheck_monitoring_jobqueue_size(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_jobqueue_size_threshold(HinemosPropertyBean.numeric(50L)),
	selfcheck_monitoring_jobqueue_deadlock(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_jobqueue_deadlock_threshold(HinemosPropertyBean.numeric(600L)),
	selfcheck_monitoring_jvm_freeheap(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_jvm_freeheap_threshold(HinemosPropertyBean.numeric(32L)),
	selfcheck_monitoring_rest_agent_queue(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_rest_agent_queue_threshold(HinemosPropertyBean.numeric(960L)),
	selfcheck_monitoring_rest_agentbinary_queue(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_rest_agentbinary_queue_threshold(HinemosPropertyBean.numeric(960L)),
	selfcheck_monitoring_rest_agenthub_queue(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_rest_agenthub_queue_threshold(HinemosPropertyBean.numeric(960L)),
	selfcheck_monitoring_rest_agentnodeconfig_queue(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_rest_agentnodeconfig_queue_threshold(HinemosPropertyBean.numeric(960L)),
	selfcheck_monitoring_rest_queue(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_rest_queue_threshold(HinemosPropertyBean.numeric(240L)),
	selfcheck_monitoring_scheduler_delay(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_scheduler_delay_threshold(HinemosPropertyBean.numeric(300L)),
	selfcheck_monitoring_snmptrap_queue(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_snmptrap_queue_threshold(HinemosPropertyBean.numeric(10000L)),
	selfcheck_monitoring_swapout(HinemosPropertyBean.bool(false)),
	selfcheck_monitoring_systemlog_queue(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_systemlog_queue_threshold(HinemosPropertyBean.numeric(10000L)),
	selfcheck_monitoring_table_size(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_table_size_list(HinemosPropertyBean.string("log.cc_event_log:20480:MBYTE,log.cc_collect_data_raw:20480:MBYTE,log.cc_collect_data_string:40960:MBYTE,log.cc_job_session:100000:COUNT")),
	selfcheck_monitoring_thread_activity(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_thread_activity_threshold(HinemosPropertyBean.numeric(300L)),
	selfcheck_monitoring_ws_agent_queue(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_ws_agent_queue_threshold(HinemosPropertyBean.numeric(960L)),
	selfcheck_monitoring_ws_agentbinary_queue(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_ws_agentbinary_queue_threshold(HinemosPropertyBean.numeric(960L)),
	selfcheck_monitoring_ws_agenthub_queue(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_ws_agenthub_queue_threshold(HinemosPropertyBean.numeric(960L)),
	selfcheck_monitoring_ws_agentnodeconfig_queue(HinemosPropertyBean.bool(true)),
	selfcheck_monitoring_ws_agentnodeconfig_queue_threshold(HinemosPropertyBean.numeric(960L)),
	selfcheck_snmp_community(HinemosPropertyBean.string("public")),
	selfcheck_snmp_port(HinemosPropertyBean.numeric(161L)),
	selfcheck_snmp_retries(HinemosPropertyBean.numeric(3L)),
	selfcheck_snmp_timeout(HinemosPropertyBean.numeric(3000L)),
	selfcheck_snmp_version(HinemosPropertyBean.string(SnmpVersionConstant.STRING_V2)),
	selfcheck_startup_delay(HinemosPropertyBean.numeric(90L)),
	selfcheck_threadpool_size(HinemosPropertyBean.numeric(4L)),
	selfcheck_evaluation_alert_cron(HinemosPropertyBean.string("0 0 9 * * ? *")),
	utility_expimp_xcloud_keyprotect_enable(HinemosPropertyBean.bool(false)),
	utility_import_unitnum_common(HinemosPropertyBean.numeric(500L)),
	utility_import_unitnum_$(HinemosPropertyBean.numeric()),
	ws_agent_address(HinemosPropertyBean.string("http://0.0.0.0:8081")),
	ws_agent_queue_size(HinemosPropertyBean.numeric(1200L)),
	ws_agent_shutdown_timeout(HinemosPropertyBean.numeric(60000L)),
	ws_agent_threadpool_size(HinemosPropertyBean.numeric(8L)),
	ws_https_request_exchange_queue_size(HinemosPropertyBean.numeric(1200L)),
	ws_https_request_exchange_reject_logging(HinemosPropertyBean.bool(false)),
	ws_https_request_exchange_thread_size(HinemosPropertyBean.numeric(8L)),
	ws_https_keystore_password(HinemosPropertyBean.string("hinemos")),
	ws_https_keystore_type(HinemosPropertyBean.string("PKCS12")),
	ws_https_keystore_path(HinemosPropertyBean.string("/opt/hinemos")),
	ws_https_protocol(HinemosPropertyBean.string("TLS")),
	worker_$_factoryclass(HinemosPropertyBean.string()),
	worker_$_thread_size(HinemosPropertyBean.numeric()),
	worker_$_queue_size(HinemosPropertyBean.numeric()),
	worker_$_shutdown_timeout(HinemosPropertyBean.numeric()),
	worker_list(HinemosPropertyBean.string(
			AsyncWorkerPlugin.NOTIFY_STATUS_TASK_FACTORY +"," + 
			AsyncWorkerPlugin.NOTIFY_EVENT_TASK_FACTORY +"," + 
			AsyncWorkerPlugin.NOTIFY_MAIL_TASK_FACTORY +"," + 
			AsyncWorkerPlugin.NOTIFY_COMMAND_TASK_FACTORY +"," + 
			AsyncWorkerPlugin.NOTIFY_LOG_ESCALATION_TASK_FACTORY +"," + 
			AsyncWorkerPlugin.NOTIFY_JOB_TASK_FACTORY +"," + 
			AsyncWorkerPlugin.CREATE_JOB_SESSION_TASK_FACTORY +"," + 
			AsyncWorkerPlugin.NOTIFY_INFRA_TASK_FACTORY + "," + 
			AsyncWorkerPlugin.NOTIFY_REST_TASK_FACTORY + "," + 
			AsyncWorkerPlugin.NOTIFY_CLOUD_TASK_FACTORY + "," + 
			AsyncWorkerPlugin.AGENT_RESTART_TASK_FACTORY + "," +
			AsyncWorkerPlugin.AGENT_UPDATE_TASK_FACTORY + "," +
			AsyncWorkerPlugin.AGENT_BROADCAST_AWAKE_TASK_FACTORY + "," +
			AsyncWorkerPlugin.AGENT_MESSAGE_LOGGER_TASK_FACTORY + "," +
			AsyncWorkerPlugin.NOTIFY_MESSAGE_TASK_FACTORY)),
	worker_async_task_persist_monitor_agent(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_custom(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_http(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_performance(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_ping(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_port(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_process(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_snmptrap(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_snmp(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_sql(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_syslog(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_logfile(HinemosPropertyBean.bool(true)),
	worker_async_task_persist_monitor_logcount(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_binaryfile(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_packetcapture(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_job(HinemosPropertyBean.bool(true)),
	worker_async_task_persist_maintenance(HinemosPropertyBean.bool(true)),
	worker_async_task_persist_monitor_winevent(HinemosPropertyBean.bool(true)),
	worker_async_task_persist_monitor_customtrap(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_correlation(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_integration(HinemosPropertyBean.bool(false)),
	worker_async_task_persist_monitor_rpalogfile(HinemosPropertyBean.bool(true)),
	worker_async_task_persist_monitor_rpamanagementtoolservice(HinemosPropertyBean.bool(true)),
	ws_queue_size(HinemosPropertyBean.numeric(300L)),

	/* xCloud用プロパティ */
	xcloud_agent_connection_count(HinemosPropertyBean.numeric(30L)),
	xcloud_agent_connection_interval(HinemosPropertyBean.numeric(10000L)),
	xcloud_autoregist_node_entity(HinemosPropertyBean.bool(true)),
	xcloud_autodelete_node_entity(HinemosPropertyBean.bool(false)),
	xcloud_autoregist_node_instance(HinemosPropertyBean.bool(true)),
	xcloud_autodelete_node_instance(HinemosPropertyBean.bool(false)),
	xcloud_autodelete_instance(HinemosPropertyBean.bool(true)),
	xcloud_autodelete_node_backupimage(HinemosPropertyBean.bool(true)),
	xcloud_instance_snapshot_count_max(HinemosPropertyBean.numeric(5L)),
	xcloud_ipaddress_cidr(HinemosPropertyBean.string("10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16")),
	xcloud_ipaddress_notavailable(HinemosPropertyBean.string("169.254.0.0")),
	xcloud_agent_connection_enable(HinemosPropertyBean.bool(true)),
	xcloud_node_property_cloud_service_update(HinemosPropertyBean.bool(true)),
	xcloud_node_property_platformfamily_update(HinemosPropertyBean.bool(true)),
	xcloud_node_property_subplatformfamily_update(HinemosPropertyBean.bool(true)),
	xcloud_node_property_nodename_update(HinemosPropertyBean.bool(true)),
	xcloud_node_property_cloud_scope_update(HinemosPropertyBean.bool(true)),
	xcloud_node_property_cloud_resourcename_update(HinemosPropertyBean.bool(true)),
	xcloud_node_property_cloud_resourcetype_update(HinemosPropertyBean.bool(true)),
	xcloud_node_property_cloud_resourceid_update(HinemosPropertyBean.bool(true)),
	xcloud_node_property_cloud_location_update(HinemosPropertyBean.bool(true)),
	xcloud_node_property_cloud_ipaddress_update(HinemosPropertyBean.bool(true)),
	xcloud_node_property_cloud_validflag_update(HinemosPropertyBean.bool(true)),
	xcloud_node_property_cloud_validflag_excludestates(HinemosPropertyBean.string("")),
	xcloud_node_property_nic_update(HinemosPropertyBean.bool(true)),
	xcloud_node_property_cloudlog_priority(HinemosPropertyBean.numeric(16L)),
	xcloud_autoupdate_agent(HinemosPropertyBean.bool(false)),
	xcloud_autoupdate_agent_cidr(HinemosPropertyBean.string("0.0.0.0/32")),
	xcloud_storage_snapshot_count_max(HinemosPropertyBean.numeric(5L)),
	xcloud_billing_detail_collect_time(HinemosPropertyBean.string("0 0 2 * * ?")),
	xcloud_autoupdate_node(HinemosPropertyBean.bool(true)),
	xcloud_registcheck_interval(HinemosPropertyBean.numeric(10000L)),
	xcloud_registcheck_count(HinemosPropertyBean.numeric(30L)),
	xcloud_autoupdate_storage_enable(HinemosPropertyBean.bool(true)),
	xcloud_autoupdate_storage_snapshot_enable(HinemosPropertyBean.bool(true)),
	xcloud_autoupdate_instance_snapshot_enable(HinemosPropertyBean.bool(true)),
	xcloud_autoupdate_interval(HinemosPropertyBean.string("0 */10 * * * ?")),
	xcloud_platform_service_monitor_interval(HinemosPropertyBean.string("0 */10 * * * ?")),
	xcloud_monitor_resource_aws_escape(HinemosPropertyBean.bool(false)),
	xcloud_monitor_resource_aws_not_add_prefix(HinemosPropertyBean.string("Backup, Glue, WAF")),
	xcloud_node_property_node_variablename(HinemosPropertyBean.string("")),
	xcloud_node_property_node_variablevalue(HinemosPropertyBean.string("")),
	xcloud_node_property_agent_awakeport(HinemosPropertyBean.numeric(24005L)),
	xcloud_node_property_job_priority(HinemosPropertyBean.numeric(16L)),
	xcloud_node_property_job_multiplicity(HinemosPropertyBean.numeric(0L)),
	xcloud_node_property_snmp_user(HinemosPropertyBean.string("root")),
	xcloud_node_property_snmp_port(HinemosPropertyBean.numeric(161L)),
	xcloud_node_property_snmp_community(HinemosPropertyBean.string("public")),
	xcloud_node_property_snmp_version(HinemosPropertyBean.string(SnmpVersionConstant.STRING_V2)),
	xcloud_node_property_snmp_securitylevel(HinemosPropertyBean.string("noauth_nopriv")),
	xcloud_node_property_snmp_auth_password(HinemosPropertyBean.string("")),
	xcloud_node_property_snmp_priv_password(HinemosPropertyBean.string("")),
	xcloud_node_property_snmp_auth_protocol(HinemosPropertyBean.string("MD5")),
	xcloud_node_property_snmp_priv_protocol(HinemosPropertyBean.string("DES")),
	xcloud_node_property_snmp_timeout(HinemosPropertyBean.numeric(5000L)),
	xcloud_node_property_snmp_retries(HinemosPropertyBean.numeric(3L)),
	xcloud_node_property_wbem_user(HinemosPropertyBean.string("root")),
	xcloud_node_property_wbem_userpassword(HinemosPropertyBean.string("")),
	xcloud_node_property_wbem_port(HinemosPropertyBean.numeric(5988L)),
	xcloud_node_property_wbem_protocol(HinemosPropertyBean.string("http")),
	xcloud_node_property_wbem_timeout(HinemosPropertyBean.numeric(5000L)),
	xcloud_node_property_wbem_retries(HinemosPropertyBean.numeric(3L)),
	xcloud_node_property_ipmi_ipaddress(HinemosPropertyBean.string("")),
	xcloud_node_property_ipmi_port(HinemosPropertyBean.numeric(0L)),
	xcloud_node_property_ipmi_user(HinemosPropertyBean.string("")),
	xcloud_node_property_ipmi_userpassword(HinemosPropertyBean.string("")),
	xcloud_node_property_ipmi_timeout(HinemosPropertyBean.numeric(5000L)),
	xcloud_node_property_ipmi_retries(HinemosPropertyBean.numeric(3L)),
	xcloud_node_property_ipmi_protocol(HinemosPropertyBean.string("RMCP+")),
	xcloud_node_property_ipmi_level(HinemosPropertyBean.string("")),
	xcloud_node_property_winrm_user(HinemosPropertyBean.string("")),
	xcloud_node_property_winrm_userpassword(HinemosPropertyBean.string("")),
	xcloud_node_property_winrm_version(HinemosPropertyBean.string("2.0")),
	xcloud_node_property_winrm_port(HinemosPropertyBean.numeric(5985L)),
	xcloud_node_property_winrm_protocol(HinemosPropertyBean.string("http")),
	xcloud_node_property_winrm_timeout(HinemosPropertyBean.numeric(5000L)),
	xcloud_node_property_winrm_retries(HinemosPropertyBean.numeric(3L)),
	xcloud_node_property_ssh_user(HinemosPropertyBean.string("root")),
	xcloud_node_property_ssh_userpassword(HinemosPropertyBean.string("")),
	xcloud_node_property_ssh_privkey_path(HinemosPropertyBean.string("")),
	xcloud_node_property_ssh_privkey_passphrase(HinemosPropertyBean.string("")),
	xcloud_node_property_ssh_port(HinemosPropertyBean.numeric(22L)),
	xcloud_node_property_ssh_timeout(HinemosPropertyBean.numeric(50000L)),
	xcloud_node_property_rpa_log_directory(HinemosPropertyBean.string("")),
	xcloud_node_property_rpa_management_tool_type(HinemosPropertyBean.string("")),
	xcloud_node_property_rpa_resource_id(HinemosPropertyBean.string("")),
	xcloud_node_property_rpa_user(HinemosPropertyBean.string("")),
	xcloud_node_property_rpa_execution_environment_id(HinemosPropertyBean.string("")),
	xcloud_node_property_administrator(HinemosPropertyBean.string("")),
	xcloud_node_property_contact(HinemosPropertyBean.string("")),
	xcloud_assign_to_multiple_scope(HinemosPropertyBean.bool(false)),
	xcloud_internal_thread_admin_user(HinemosPropertyBean.string("hinemos")),
	xcloud_python_status_confirm_default_timeout(HinemosPropertyBean.numeric(300L)),
	xcloud_python_status_confirm_default_interval(HinemosPropertyBean.numeric(5L)),
	xcloud_cloudlog_agent_monitor_interval(HinemosPropertyBean.numeric(30000L)),
	xcloud_power_node_update_validflag(HinemosPropertyBean.bool(false)),
	
	/* SDML用プロパティ */
	sdml_control_log_reception_max_period_buffer(HinemosPropertyBean.numeric(10L)),
	sdml_internal_check_enable(HinemosPropertyBean.bool(true)),
	sdml_internal_check_interval(HinemosPropertyBean.numeric(150L)),
	sdml_internal_check_startup_deray(HinemosPropertyBean.numeric(90L)),
	sdml_monitor_setting_id_prefix(HinemosPropertyBean.string("SDML")),
	
	// Grafanaデータソースプラグインで利用するAPIから返す最大件数
	grafana_query_event_aggregation_max_count(HinemosPropertyBean.numeric(100L)),
	grafana_query_status_aggregation_max_count(HinemosPropertyBean.numeric(100L)),
	grafana_query_job_history_aggregation_max_count(HinemosPropertyBean.numeric(100L)),
	grafana_query_job_last_run_time_max_count(HinemosPropertyBean.numeric(100L)),

	;

	// Hinemosプロパティ情報
	private final HinemosPropertyBean bean;

	/**
	 * コンストラクタ
	 * @param bean Hinemosプロパティ情報
	 */
	private HinemosPropertyCommon(HinemosPropertyBean bean) {
		this.bean = bean;
	}

	/**
	 * Hinemosプロパティ情報取得
	 * 
	 * @return Hinemosプロパティ情報
	 */
	@Override
	public HinemosPropertyBean getBean() {
		return this.bean;
	}

	/**
	 * キー値変換
	 * 名前を"_"から"."に変換
	 * $は置換文字列に変換
	 * 例）　COMMON_$_OFFSET、置換文字列"time" → common.time.offset
	 * 
	 * @param replaceStr 置換文字列
	 * @return 変換後のキー
	 */
	@Override
	public String getReplaceKey(String replaceStr) {
		if (this == HinemosPropertyCommon.mail_$_auth_digest_md5_disable) {
			return "mail.$.auth.digest-md5.disable".replace("$", replaceStr);
		} else {
			return getKey().replace("$", replaceStr);
		}
	}

	/**
	 * Hinemosプロパティ（agent.connection.ipaddres）取得
	 * 存在しない場合はデフォルト値を使用
	 * ※デフォルト値がExceptionが発生するため、独自実装
	 * 
	 * @return Hinemosプロパティ値
	 */
	public String getAgentConnectionIpaddres() throws NullPointerException, UnknownHostException {
		HinemosPropertyBean bean = getBean();
		if (bean.getType() != HinemosPropertyTypeConstant.TYPE_STRING
				|| this != HinemosPropertyCommon.agent_connection_ipaddres) {
			throw new NullPointerException();
		}
		HinemosPropertyInfo info = new HinemosPropertyControllerBean().getHinemosPropertyInfo_None(getKey());
		if (info == null 
				|| info.getValueType() != HinemosPropertyTypeConstant.TYPE_STRING
				|| info.getValueString() == null 
				|| info.getValueString().isEmpty()) {
			return InetAddress.getLocalHost().getHostAddress();
		}
		return info.getValueString();
	}
}
