/*
 * Copyright (c) 2022 NTT DATA INTELLILINK Corporation.
 *
 * Hinemos (http://www.hinemos.info/)
 *
 * See the LICENSE file for licensing information.
 */
package com.clustercontrol.xcloud.common;

import com.clustercontrol.xcloud.CloudManagerException;
import com.clustercontrol.xcloud.util.CloudMessage;

public enum ErrorCode {
	UNEXPECTED("unexpected"),
	HINEMOS_MANAGER_ERROR(),

	HINEMOS_SCOPE_DUPLICATED("XCLOUD_CORE_MSG_ENTITY_INVALID_PK2_NOT_FOUND"),
	
	LOCATION_NOT_FOUND("XCLOUD_CORE_MSG_LOCATION_NOT_FOUND"),
	
	ENDPOINT_INVALID_ENDPOINT_FOUND("XCLOUD_CORE_MSG_ENTITY_INVALID_PK2_NOT_FOUND"),
	
	CLOUDINSTANCE_NOT_ACQUIRE_LOCK("XCLOUD_CORE_MSG_ENTITY_INVALID_PK2_NOT_FOUND"),
	
	COMMUNITY_EDITION_FUNC_NOT_AVAILABLE("XCLOUD_CORE_MSG_COMMUNITY_EDITION_FUNC_NOT_AVAILABLE"),
	
	CLOUDINSTANCE_NOT_FOUND_PLATFORMINSTANANCE("XCLOUD_CORE_MSG_CLOUDINSTANCE_NOT_FOUND_PLATFORMINSTANANCE"),
	
	CLOUDENTITY_NOT_FOUND_PLATFORMENTITY("XCLOUD_CORE_MSG_ENTITY_INVALID_PK3_NOT_FOUND"),
	
	AUTOASSIGNENODEPATTERN_NOT_FOUND("XCLOUD_CORE_MSG_ENTITY_INVALID_PK2_NOT_FOUND"),
	
	UNSUPPORTED_OPERATION("XCLOUD_CORE_MSG_UNSUPPORTED_OPERATION"),
	
	AUTO_ASSIGN_NODE_UNMATCHED_CIDR_FORMAT("XCLOUD_CORE_MSG_AUTO_ASSIGN_NODE_UNMATCHED_CIDR_FORMAT"),
	AUTO_ASSIGN_NODE_UNMATCHED_REGEX("XCLOUD_CORE_MSG_AUTO_ASSIGN_NODE_UNMATCHED_REGEX"),
	AUTO_CONTROL_NOT_FOUND_SCRIPT("XCLOUD_CORE_MSG_AUTO_CONTROL_NOT_FOUND_SCRIPT"),
	AUTO_CONTROL_NOT_FOUND_INSTANCE("XCLOUD_CORE_MSG_AUTO_CONTROL_NOT_FOUND_INSTANCE"),
	AUTO_CONTROL_NOT_FOUND_STORAGE("XCLOUD_CORE_MSG_AUTO_CONTROL_NOT_FOUND_STORAGE"),
	
	CLOUDINSTANCE_FIAL_TO_POWERON_INSTANCE_BY_FACILITY("XCLOUD_CORE_MSG_CLOUDINSTANCE_FIAL_TO_POWERON_INSTANCE_BY_FACILITY"),
	CLOUDINSTANCE_FIAL_TO_POWEROFF_INSTANCE_BY_FACILITY("XCLOUD_CORE_MSG_CLOUDINSTANCE_FIAL_TO_POWEROFF_INSTANCE_BY_FACILITY"),
	CLOUDINSTANCE_FIAL_TO_REBOOT_INSTANCE_BY_FACILITY("XCLOUD_CORE_MSG_CLOUDINSTANCE_FIAL_TO_REBOOT_INSTANCE_BY_FACILITY"),
	CLOUDINSTANCE_FIAL_TO_SUSPEND_INSTANCE_BY_FACILITY("XCLOUD_CORE_MSG_CLOUDINSTANCE_FIAL_TO_SUSPEND_INSTANCE_BY_FACILITY"),
	CLOUDINSTANCE_FIAL_TO_SNAPSHOT_INSTANCE_BY_FACILITY("XCLOUD_CORE_MSG_CLOUDINSTANCE_FIAL_TO_SNAPSHOT_INSTANCE_BY_FACILITY"),
	
	CLOUD_PLATFORM_NOT_FOUND("XCLOUD_CORE_MSG_CLOUD_PLATFORM_NOT_FOUND"),
	
	LOGINUSER_NUM_NOT_MATCH("XCLOUD_CORE_MSG_LOGINUSER_NUM_NOT_MATCH"),
	LOGINUSER_USER_NOT_INCLUDE("XCLOUD_CORE_MSG_LOGINUSER_USER_NOT_INCLUDE"),
	
	CLOUDREGION_INVALID_CLOUDREGION_NOT_FOUND("XCLOUD_CORE_MSG_ENTITY_INVALID_PK2_NOT_FOUND"),
	CLOUDSCOPE_ALREADY_EXIST("XCLOUD_CORE_MSG_CLOUDSCOPE_ALREADY_EXIST"),
	CLOUDSCOPE_INVALID_CLOUDSCOPE_NOT_FOUND("XCLOUD_CORE_MSG_CLOUDSCOPE_INVALID_CLOUDSCOPE_NOT_FOUND"),
	LOGINUSER_ALREADY_EXIST("XCLOUD_CORE_MSG_LOGINUSER_ALREADY_EXIST"),
	LOGINUSER_NOT_FOUND("XCLOUD_CORE_MSG_ENTITY_INVALID_PK_NOT_FOUND"),
	LOGINUSER_NOT_ASSIGNED_TO_ROLE("XCLOUD_CORE_MSG_LOGINUSER_NOT_ASSIGNED_TO_ROLE"),
	CLOUDINSTANCE_ALREADY_EXIST("XCLOUD_CORE_MSG_CLOUDINSTANCE_ALREADY_EXIST"),
	CLOUDINSTANCE_NOT_FOUND("XCLOUD_CORE_MSG_ENTITY_INVALID_PK_NOT_FOUND"),
	CLOUDINSTANCE_NOT_FOUND_BY_FACILITY("XCLOUD_CORE_MSG_CLOUDINSTANCE_NOT_FOUND_BY_FACILITY"),
	CLOUDSTORAGE_NOT_FOUND("XCLOUD_CORE_MSG_ENTITY_INVALID_PK_NOT_FOUND"),
	CLOUDSTORAGE_ALREADY_EXIST("XCLOUD_CORE_MSG_CLOUDSTORAGE_ALREADY_EXIST"),
	CLOUDINSTANCEBACKUP_NOT_FOUND("XCLOUD_CORE_MSG_ENTITY_INVALID_PK_NOT_FOUND"),
	CLOUDSTORAGEBACKUP_NOT_FOUND("XCLOUD_CORE_MSG_ENTITY_INVALID_PK_NOT_FOUND"),
	
	MONITOR_CLOUDSERVICE_FOUND_NO_SERVICEID("XCLOUD_CORE_MSG_MONITOR_CLOUDSERVICE_FOUND_NO_SERVICEID"),
	MONITOR_CLOUDSERVICE_ONLY_NODE("XCLOUD_CORE_MSG_MONITOR_CLOUDSERVICE_ONLY_NODE"),
	
	AUTOUPDATE_NOT_DELETE_FACILITY("XCLOUD_CORE_MSG_AUTOUPDATE_NOT_DELETE_FACILITY"),
	
	BILLINGALARM_INVALID_OWNERROLEID("XCLOUD_CORE_MSG_BILLINGALARM_INVALID_OWNERROLEID"),
	BILLINGALARM_ALREADY_EXIST("XCLOUD_CORE_MSG_BILLINGALARM_ALREADY_EXIST"),
	BILLINGALARM_NOT_FOUND("XCLOUD_CORE_MSG_BILLINGALARM_NOT_FOUND"),
	BILLINGALARM_NOT_FOUND_BY_HINEMOSUSER("XCLOUD_CORE_MSG_BILLINGALARM_NOT_FOUND_BY_HINEMOSUSER"),
	
	NEED_ADMINISTRATORS_ROLE("XCLOUD_CORE_MSG_NEED_ADMINISTRATORS_ROLE"),
	NEED_ADMINISTRATORS_ROLE_OR_ACCOUNT_USER("XCLOUD_CORE_MSG_NEED_ADMINISTRATORS_ROLE_OR_ACCOUNT_USER"),
	NEED_ADMINISTRATORS_ROLE_OR_ACCOUT_USER_OR_SELF("XCLOUD_CORE_MSG_NEED_ADMINISTRATORS_ROLE_OR_ACCOUT_USER_OR_SELF"),
	
	OBJECTPRIVILEGE_NOT_FOUND_TARGET_OBJECT("XCLOUD_CORE_MSG_OBJECTPRIVILEGE_NOT_FOUND_TARGET_OBJECT"),
	OBJECTPRIVILEGE_UNAUTHORIZED_TO_TARGET_OBJECT("XCLOUD_CORE_MSG_OBJECTPRIVILEGE_UNAUTHORIZED_TO_TARGET_OBJECT"),
	
	FACILITY_NOT_FOUND("XCLOUD_CORE_MSG_FACILITY_NOT_FOUND"),
	SCOPE_FACILITY_DUPLICATE("XCLOUD_CORE_MSG_SCOPE_FACILITY_DUPLICATE"),
	
	ALREADY_ASSIGN_NODE("XCLOUD_CORE_MSG_ALREADY_ASSIGN_NODE"),
	
	AGENT_NOT_FOUND("Timed-out. Agent not found."),
	
	VALIDATION_ERROR("VALIDATION_ERROR"),
	
	UPDATE_ALREADY_RUNNING_FOR_RESOURCE("XCLOUD_CORE_MSG_UPDATE_ALREADY_RUNNING_FOR_RESOURCE")
	;

	private String messageId;

	private ErrorCode() {
	}

	private ErrorCode(String messageId) {
		this.messageId = messageId;
	}

	public boolean match(String errorCode) {
		return name().equals(errorCode);
	}

	public boolean match(CloudManagerException e) {
		return name().equals(e.getErrorCode());
	}

	public String getMessage(String... args) {
		return CloudMessage.getMessage(messageId, args);
	}

	public CloudManagerException cloudManagerFault(String... args) {
		return new CloudManagerException(getMessage(args), this.name());
	}

	public CloudManagerException cloudManagerFault(Exception e) {
		return new CloudManagerException(e.getMessage(), this.name(), e);
	}

	public CloudManagerException cloudManagerFault(Exception e, String... args) {
		return new CloudManagerException(getMessage(args), this.name(), e);
	}
}
